ability_list = [
    "Empty",
    "Aerial Dive",
    "Aerial Dodge LV1",
    "Aerial Dodge LV2",
    "Aerial Dodge LV3",
    "Aerial Dodge MAX",
    "Aerial Finish",
    "Aerial Impulse",
    "Aerial Recovery",
    "Aerial Spiral",
    "Aerial Sweep",
    "Air Combo Boost",
    "Air Combo Plus",
    "Applause, Applause",
    "Ars Arcanum",
    "Auto Assault",
    "Auto Change",
    "Auto Final",
    "Auto Healing",
    "Auto Limit",
    "Auto Limit Form",
    "Auto Master",
    "Auto Summon",
    "Auto Valor",
    "Auto Wisdom",
    "Berserk Charge",
    "Blazing Fury",
    "Blizzard Boost",
    "Bolts of Sorrow",
    "Bone Smash",
    "Brave Beat",
    "Brave Shot",
    "Combo Boost",
    "Combo Master",
    "Combo Plus",
    "Combo Upper",
    "Combination Boost",
    "Complete Compilement",
    "Counterguard",
    "Crime & Punishment",
    "Cure Potion",
    "Damage Control",
    "Damage Drive",
    "Dark Aura",
    "Dark Shield",
    "Dash",
    "Defender",
    "Disaster",
    "Divider",
    "Dodge Roll LV 1",
    "Dodge Roll LV 2",
    "Dodge Roll LV 3",
    "Dodge Roll MAX",
    "Dodge Slash",
    "Donald Blizzard",
    "Donald Cure",
    "Donald Fire",
    "Donald Thunder",
    "Draw",
    "Drive Boost",
    "Drive Converter",
    "Dragonblaze",
    "Endless Magic",
    "Eternal Session",
    "Explosion",
    "Experience Boost",
    "Fantasia",
    "Ferocious Rush",
    "Final Arcana",
    "Final Arts",
    "Final Strike",
    "Finishing Blast",
    "Finishing Leap",
    "Finishing Plus",
    "Fire Boost",
    "Firaga Bangle",
    "Fierce Claw",
    "Flash Step",
    "Flametongue",
    "Flare Force",
    "Form Boost",
    "Furious Shout",
    "Glide LV1",
    "Glide LV2",
    "Glide LV3",
    "Glide MAX",
    "Goofy Bash",
    "Goofy Tornado",
    "Goofy Turbo",
    "Groundshaker",
    "Guard",
    "Guard Break",
    "Healing Herb",
    "Healing Water",
    "High Jump LV1",
    "High Jump LV2",
    "High Jump LV3",
    "High Jump MAX",
    "Horizontal Slash",
    "Howling Moon",
    "Hurricane Period",
    "HP Gain",
    "Hyper Healing",
    "Icy Terror",
    "Item Boost",
    "Jackpot",
    "King's Pride",
    "Leaf Bracer",
    "Light & Darkness",
    "Lucky Lucky",
    "Magic Haste",
    "Magic Lock-On",
    "Magic Spice",
    "Magnet Burst",
    "Master Magic",
    "Master Strike",
    "Mobile Action",
    "MP Haste",
    "MP Hastega",
    "MP Hastera",
    "MP Rage",
    "Mushu Fire",
    "Negative Combo",
    "No Experience",
    "No Mercy",
    "Omega Finale",
    "Once More",
    "Over the Horizon",
    "Overdrive",
    "Pulsing Thunder",
    "Protect",
    "Protectga",
    "Protectra",
    "Quick Run LV1",
    "Quick Run LV2",
    "Quick Run LV3",
    "Quick Run MAX",
    "Quickplay",
    "Rain Storm",
    "Ragnarok",
    "Reaction Boost",
    "Reflect Combo",
    "Reflect Dummy",
    "Retaliating Slash",
    "Retaliating Smash",
    "Ripple Drive",
    "Running Tackle",
    "Scan",
    "Scouting Disk",
    "Second Chance",
    "Slash Frenzy",
    "Slapshot",
    "Slide Dash",
    "Slow 2",
    "Slow 3",
    "Sonic Blade",
    "Sonic End",
    "Sonic Strike",
    "Strike Raid",
    "Summon Boost",
    "Synch Blade",
    "Teamwork",
    "Thunder Boost",
    "Tornado Fusion",
    "Treasure Isle",
    "Trick Fantasy",
    "Trinity Limit",
    "Upper Dummy",
    "Upper Slash",
    "Vicinity Break",
    "Wisdom Shot",
    "Zantetsu Counter",
    "Zantetsuken",
]