heartless_dict = {
    "Soldier": 0x00,
    "Shadow": 0x01,
    "Large Body": 0x02,
    "Neoshadow": 0x03,
    "Trick Ghost": 0x04,
    "Rabid Dog": 0x05,
    "Hook Bat": 0x06,
    "Bookmaster": 0x07,
    "Aeroplane": 0x08,
    "Minute Bomb": 0x09,
    "Hammer Frame": 0x0A,
    "Assault Rider": 0x0B,
    "Nightwalker": 0x0C,
    "Bulky Vendor": 0x0D,
    "Magnum Loader": 0x0E,
    "Strafer": 0x0F,
    "Fortuneteller": 0x10,
    "Luna Bandit": 0x11,
    "Hot Rod": 0x12,
    "Cannon Gun": 0x13,
    "Rapid Thruster": 0x14,
    "Living Bone": 0x15,
    "Devastator": 0x16,
    "Lance Soldier": 0x17,
    "Driller Mole": 0x18,
    "Morning Star": 0x19,
    "Shaman": 0x1A,
    "Tornado Step": 0x1B,
    "Armored Knight": 0x1C,
    "Surveillance Robot": 0x1D,
    "Fiery Globe": 0x1E,
    "Icy Cube": 0x1F,
    "Gargoyle Knight": 0x20,
    "Gargoyle Warrior": 0x21,
    "Silver Rock": 0x22,
    "Emerald Blues": 0x23,
    "Crimson Jazz": 0x24,
    "Bolt Tower": 0x25,
    "Aerial Knocker": 0x27,
    "Fat Bandit": 0x28,
    "Toy Soldier": 0x29,
    "Wight Knight": 0x2A,
    "Air Pirate": 0x2B,
    "Crescendo": 0x2C,
    "Creeper Plant": 0x2D,
    "Graveyard": 0x2E,
    # CoR Heartless
    "Spring Metal": 0x3C,
    "Aerial Viking": 0x3D,
    "Magic Phantom": 0x3E,
    "Beffudler": 0x3F,
    "Runemaster": 0x40,
    "Iron Hammer": 0x41,
    "Mad Ride": 0x42,
    "Camo Cannon": 0x43,
    "Reckless": 0x44,
    "Lance Warrior": 0x45,
    "Necromancer": 0x46,
    "Aerial Champ": 0x47,
}
heartless_list = [
    "Shadow",
    "Soldier",
    "Large Body",
    "Silver Rock",
    "Emerald Blues",
    "Crimson Jazz",
    "Air Pirate",
    "Trick Ghost",
    "Rabid Dog",
    "Hook Bat",
    "Bookmaster",
    "Minute Bomb",
    "Hammer Frame",
    "Bulky Vendor",
    "Fortuneteller",
    "Cannon Gun",
    "Rapid Thruster",
    "Driller Mole",
    "Lance Soldier",
    "Morning Star",
    "Fiery Globe",
    "Icy Cube",
    "Fat Bandit",
    "Luna Bandit",
    "Gargoyle Knight",
    "Gargoyle Warrior",
    "Wight Knight",
    "Graveyard",
    "Toy Soldier",
    "Aeroplane",
    "Hot Rod",
    "Assault Rider",
    "Nightwalker",
    "Bolt Tower",
    "Magnum Loader",
    "Strafer",
    "Devastator",
    "Living Bone",
    "Shaman",
    "Aerial Knocker",
    "Tornado Step",
    "Crescendo",
    "Creeper Plant",
    "Armored Knight",
    "Surveillance Robot",
    "Neoshadow",
    "Spring Metal",
    "Aerial Viking",
    "Magic Phantom",
    "Beffudler",
    "Runemaster",
    "Iron Hammer",
    "Mad Ride",
    "Camo Cannon",
    "Reckless",
    "Lance Warrior",
    "Necromancer",
    "Aerial Champ",
]
boss_list = [
    "Volcanic Lord",
    "Blizzard Lord",
    "Thresholder",
    "Possessor",
    "Shadow Stalker",
    "Dark Thorn",
    "Illuminator",
    "Grim Reaper",
    "Groundshaker",
    "Prison Keeper",
    "Storm Rider",
]
nobody_dict = {
    "Dusk": 0x00,
    "Dragoon": 0x03,
    "Assassin": 0x04,
    "Samurai": 0x05,
    "Sniper": 0x06,
    "Dancer": 0x07,
    "Berserker": 0x08,
    "Gambler": 0x09,
    "Sorcerer": 0x0A,
    "Creeper": 0x0B,
}
nobody_list = [
    "Dusk",
    "Creeper",
    "Dragoon",
    "Assassin",
    "Samurai",
    "Sniper",
    "Dancer",
    "Berserker",
    "Gambler",
    "Sorcerer",
]
rc_dict = {
    "Cyclone": 0x00,
    "Kickback": 0x01,
    "Full Swing 1": 0x02,
    "Bat Cry": 0x03,
    "Clear Shot": 0x04,
    "Lance Tug": 0x05,
    "Full Swing 2": 0x06,
    "Dodge Roll": 0x07,
    "Speed Trap": 0x08,
    "Root Ravager": 0x09,
    "Tornado Ride": 0x0A,
    "Heal Stomp": 0x0B,
    "Quick Blade": 0x0C,
    "Shift Shot": 0x0D,
    "Air Twister": 0x0E,
    "Wind Dance": 0x0F,
    "Rising Sun": 0x10,
    "Snag": 0x11,
    "Rapid Blow": 0x12,
    "Dispel": 0x13,
    "Rodeo": 0x14,
    "Reversal": 0x15,
    "Duel Stance": 0x16,
    "Learn": 0x17,
    "Warp Snipe": 0x18,
    "Stop Dice": 0x19,
    "Begin Game": 0x1A,
    "Aero Blade": 0x1B,
    # Skip
    "Berserk": 0x1D,
    "Bolt Reversal": 0x1E,
    # Skips
    "Sparkle Ray": 0x22,
    "Bump": 0x23,
    "Meteor Spike": 0x24,
    "Grand Cross": 0x25,
    "Jump": 0x26,
    # Skip
    "Guard": 0x28,
    "Capsule Prize": 0x29,
    "Rare Capsule": 0x2A,
    "Limited Capsule": 0x2B,
    "Prime Capsule": 0x2C,
    "Release 1": 0x2D,
    "Fail-Safe": 0x2E,
    "Release 2": 0x2F,
}
rc_list_dict = {
    "Soldier": [
        "Cyclone",
    ],
    "Large Body": [
        "Guard",
        "Full Swing 1",
        "Kickback",
    ],
    "Silver Rock": [
        "Shift Shot",
    ],
    "Air Pirate": [
        "Air Twister",
    ],
    "Hook Bat": [
        "Bat Cry",
    ],
    "Minute Bomb": [
        "Dodge Roll",
    ],
    "Bulky Vendor": [
        "Prime Capsule",
        "Limited Capsule",
        "Rare Capsule",
        "Capsule Prize",
    ],
    "Fortuneteller": [
        "Clear Shot",
    ],
    "Rapid Thruster": [
        "Aero Blade",
        "Speed Trap",
    ],
    "Lance Soldier": [
        "Lance Tug",
    ],
    "Morning Star": [
        "Meteor Spike",
        "Bump",
    ],
    "Fat Bandit": [
        "Full Swing 2",
    ],
    "Gargoyle Knight": [
        "Release 1",
    ],
    "Gargoyle Warrior": [
        "Release 2",
    ],
    "Bolt Tower": [
        "Bolt Reversal",
    ],
    "Magnum Loader": [
        "Quick Blade",
    ],
    "Living Bone": [
        "Grand Cross",
        "Rodeo",
    ],
    "Shaman": [
        "Dispel",
    ],
    "Aerial Knocker": [
        "Rapid Blow",
    ],
    "Tornado Step": [
        "Tornado Ride",
    ],
    "Crescendo": [
        "Heal Stomp",
    ],
    "Creeper Plant": [
        "Root Ravager",
    ],
    "Armored Knight": [
        "Rising Sun",
    ],
    "Surveillance Robot": [
        "Sparkle Ray",
        "Snag",
    ],
    "Neoshadow": [
        "Wind Dance",
    ],
    "Dusk": [
        "Reversal",
    ],
    "Dragoon": [
        "Jump",
        "Learn",
    ],
    "Assassin": [
        "Fail-Safe",
    ],
    "Samurai": [
        "Duel Stance",
    ],
    "Sniper": [
        "Warp Snipe",
    ],
    "Berserker": [
        "Berserk",
    ],
    "Gambler": [
        "Begin Game",
        "Stop Dice",
    ],
}
limit_dict = {
    "Overdrive": 0x00,
    "Howling Moon": 0x01,
    "Dragonblaze": 0x02,
    "Twister Fusion": 0x03,
    "Teamwork": 0x04,
    "Fantasia": 0x05,
    "Flare Force": 0x06,
    "Trick Fantasy": 0x07,
    "Treasure Isle": 0x08,
    "King's Pride": 0x09,
    "Applause, Applause": 0x0A,
    "Complete Compilement": 0x0B,
    "Eternal Session": 0x0C,
    "Trinity Limit": 0x0D,
    "Never Land": 0x0E,
    "Ohana!": 0x0F,
    "FPS Mode": 0x10,
    "Genie Sonic Blade": 0x11,
    "Genie Strike Raid": 0x12,
    "Genie Ars Arcanum": 0x13,
    "Genie Ragnarok": 0x14,
}
limit_list = [
    "Fantasia",
    "Flare Force",
    "Twister Fusion",
    "Teamwork",
    "Howling Moon",
    "Overdrive",
    "Dragonblaze",
    "Trick Fantasy",
    "Applause, Applause",
    "Treasure Isle",
    "King's Pride",
    "Complete Compilement",
    "Eternal Session",
    "Trinity Limit",
    "Never Land",
    "FPS Mode",
    "Ohana!",
    "Genie Sonic Blade",
    "Genie Strike Raid",
    "Genie Ars Arcanum",
    "Genie Ragnarok",
]
