export function command_dicts(obj) {
    obj.command_dict = {
        "Empty": 0x00,
        "Attack": 0x01,
        "Magic": 0x02,
        "Items": 0x03,
        "Drive": 0x04,
        "Revert": 0x05,
        "Valor Form": 0x06,
        "Wisdom Form": 0x07,
        "-": 0x09,
        "Talk": 0x0A,
        "Master Form": 0x0B,
        "Final Form": 0x0C,
        "Antiform": 0x0D,
        "Search": 0x0E,
        "Hi-Potion": 0x14,
        "Ether": 0x15,
        "Elixir": 0x16,
        "Potion": 0x17,
        "Reversal": 0x18,
        "Full Swing": 0x19,
        "Tackle": 0x1A,
        "Fire": 0x31,
        "Thunder": 0x32,
        "Blizzard": 0x33,
        "Cure": 0x34,
        "Fira": 0x77,
        "Firaga": 0x78,
        "Blizzara": 0x79,
        "Blizzaga": 0x7A,
        "Thundara": 0x7B,
        "Thundaga": 0x7C,
        "Cura": 0x7D,
        "Curaga": 0x7E,
        "Magnet": 0xAE,
        "Magnera": 0xAF,
        "Magnega": 0xB0,
        "Reflect": 0xB1,
        "Reflera": 0xB2,
        "Reflega": 0xB3,
        "Mega-Potion": 0xF2,
        "Mega-Ether": 0xF3,
        "Megalixir": 0xF4,
        "Limit Form": 0x02A1,
        "Ragnarok": 0x02AB,
        "Sonic Blade": 0x02BA,
        "Ars Arcanum": 0x02BD,
        "Strike Raid": 0x02C0,
    }
    obj.shortcut_list = [
        "Empty",
        "Fire", "Fira", "Firaga",
        "Blizzard", "Blizzara", "Blizzaga",
        "Thunder", "Thundara", "Thundaga",
        "Cure", "Cura", "Curaga",
        "Magnet", "Magnera", "Magnega",
        "Reflect", "Reflera", "Reflega",
        "Potion", "Hi-Potion", "Mega-Potion",
        "Ether", "Mega-Ether",
        "Elixir", "Megalixir",
        "Valor Form", "Wisdom Form", "Limit Form",
        "Master Form", "Final Form", "Antiform",
    ]
    obj.limit_form_shortcut_list = [
        "Empty",
        "Sonic Blade",
        "Ars Arcanum",
        "Strike Raid",
        "Ragnarok",
    ]
}
