weapon_dict = {
    "Sora": [
        "Empty",
        "Kingdom Key",
        "Oathkeeper",
        "Oblivion",
        "Star Seeker",
        "Hidden Dragon",
        "Hero's Crest",
        "Monochrome",
        "Follow the Wind",
        "Circle of Life",
        "Photon Debugger",
        "Gull Wing",
        "Rumbling Rose",
        "Guardian Soul",
        "Wishing Lamp",
        "Decisive Pumpkin",
        "Sleeping Lion",
        "Sweet Memories",
        "Mysterious Abyss",
        "Fatal Crest",
        "Bond of Flame",
        "Fenrir",
        "Ultima Weapon",
        "Two Become One",
        "Winner's Proof",
        "Struggle Sword",
        "Struggle Wand",
        "Struggle Hammer",
        "Detection Saber",
        "Edge/Frontier of Ultima",
        "Antiform Dummy",
    ],
    "Donald": [
        "Empty",
        "Mage's Staff",
        "Hammer Staff",
        "Victory Bell",
        "Meteor Staff",
        "Comet Staff",
        "Lord's Broom",
        "Wisdom Wand",
        "Rising Dragon",
        "Nobody Lance",
        "Shaman's Relic",
        "Shaman's Relic+",
        "Save the Queen",
        "Save the Queen+",
        "Centurion",
        "Centurion+",
        "Plain Mushroom",
        "Plain Mushroom+",
        "Precious Mushroom",
        "Precious Mushroom+",
        "Premium Mushroom",
        "Staff of Detection",
    ],
    "Goofy": [
        "Empty",
        "Knight's Shield",
        "Adamant Shield",
        "Chain Gear",
        "Ogre Shield",
        "Falling Star",
        "Dreamcloud",
        "Knight Defender",
        "Genji Shield",
        "Akashic Record",
        "Akashic Record+",
        "Nobody Guard",
        "Save the King",
        "Save the King+",
        "Frozen Pride",
        "Frozen Pride+",
        "Joyous Mushroom",
        "Joyous Mushroom+",
        "Majestic Mushroom",
        "Majestic Mushroom+",
        "Ultimate Mushroom",
        "Detection Shield",
        "Test the King",
    ],
    "Guest": [
        "Empty",
        "Kingdom Key W",
        "Battlefields of War",
        "Sword of the Ancestor",
        "Sword of the Ancestor (FAKE)",
        "Beast's Claw",
        "Bone Fist",
        "Proud Fang",
        "Skill and Crossbones",
        "Scimitar",
        "Identity Disk",
        "Way to the Dawn",
    ]
}
armor_list = [
    "Empty",
    "Elven Bandanna",
    "Divine Bandanna",
    "Protect Belt",
    "Gaia Belt",
    "Power Band",
    "Buster Band",
    "Cosmic Belt",
    "Fire Bangle",
    "Fira Bangle",
    "Firaga Bangle",
    "Firagun Bangle",
    "Blizzard Armlet",
    "Blizzara Armlet",
    "Blizzaga Armlet",
    "Blizzagun Armlet",
    "Thunder Trinket",
    "Thundara Trinket",
    "Thundaga Trinket",
    "Thundagun Trinket",
    "Shock Charm",
    "Shock Charm+",
    "Shadow Anklet",
    "Dark Anklet",
    "Midnight Anklet",
    "Chaos Anklet",
    "Champion Belt",
    "Abas Chain",
    "Aegis Chain",
    "Acrisius",
    "Acrisius+",
    "Cosmic Chain",
    "Petite Ribbon",
    "Ribbon",
    "Grand Ribbon",
]
accessory_list = [
    "Empty",
    "Ability Ring",
    "Engineer's Ring",
    "Technician's Ring",
    "Skill Ring",
    "Skillful Ring",
    "Expert's Ring",
    "Master's Ring",
    "Cosmic Ring",
    "Executive's Ring",
    "Sardonyx Ring",
    "Tourmaline Ring",
    "Aquamarine Ring",
    "Garnet Ring",
    "Diamond Ring",
    "Silver Ring",
    "Gold Ring",
    "Platinum Ring",
    "Mythril Ring",
    "Orichalcum Ring",
    "Soldier Earring",
    "Fencer Earring",
    "Mage Earring",
    "Slayer Earring",
    "Medal",
    "Moon Amulet",
    "Star Charm",
    "Cosmic Arts",
    "Shadow Archive",
    "Shadow Archive+",
    "Full Bloom",
    "Full Bloom+",
    "Draw Ring",
    "Lucky Ring",
]