export function item_dicts(obj) {
    obj.item_dict = {
        "Empty": 0x00,
        "Potion": 0x01,
        "Hi-Potion": 0x02,
        "Ether": 0x03,
        "Elixir": 0x04,
        "Mega-Potion": 0x05,
        "Mega-Ether": 0x06,
        "Megalixir": 0x07,
        "Ability Ring": 0x08,
        "Engineer's Ring": 0x09,
        "Technician's Ring": 0x0A,
        "Expert's Ring": 0x0B,
        "Sardonyx Ring": 0x0C,
        "Tourmaline Ring": 0x0D,
        "Aquamarine Ring": 0x0E,
        "Garnet Ring": 0x0F,
        "Diamond Ring": 0x10,
        "Silver Ring": 0x11,
        "Gold Ring": 0x12,
        "Platinum Ring": 0x13,
        "Mythril Ring": 0x14,
        "Fire Element": 0x15,
        "Blizzard Element": 0x16,
        "Thunder Element": 0x17,
        "Cure Element": 0x18,
        "Ukulele Charm": 0x19,
        "Valor Form": 0x1A,
        "Wisdom Form": 0x1B,
        "Orichalcum Ring": 0x1C,
        "Final Form": 0x1D,
        "Antiform": 0x1E,
        "Master Form": 0x1F,
        "Torn Pages": 0x20,
        "Unused 0x21": 0x21,
        "Master's Ring": 0x22,
        "Moon Amulet": 0x23,
        "Star Charm": 0x24,
        "Unused 0x25": 0x25,
        "Skill Ring": 0x26,
        "Skillful Ring": 0x27,
        "Soldier Earring": 0x28,
        "Kingdom Key": 0x29,
        "Oathkeeper": 0x2A,
        "Oblivion": 0x2B,
        "Detection Saber": 0x2C,
        "Edge/Frontier of Ultima": 0x2D,
        "Fencer Earring": 0x2E,
        "Mage Earring": 0x2F,
        "Slayer Earring": 0x30,
        "Knight's Shield": 0x31,
        "Detection Shield": 0x32,
        "Test the King": 0x33,
        "Cosmic Ring": 0x34,
        "Medal": 0x35,
        "Battlefields of War": 0x36,
        "Sword of the Ancestor": 0x37,
        "Cosmic Arts": 0x38,
        "Shadow Archive": 0x39,
        "Shadow Archive+": 0x3A,
        "Beast's Claw": 0x3B,
        "Bone Fist": 0x3C,
        "Proud Fang": 0x3D,
        "Skill and Crossbones": 0x3E,
        "Lucky Ring": 0x3F,
        "Full Bloom": 0x40,
        "Draw Ring": 0x41,
        "Full Bloom+": 0x42,
        "Elven Bandanna": 0x43,
        "Divine Bandanna": 0x44,
        "Power Band": 0x45,
        "Buster Band": 0x46,
        "Antiform Dummy": 0x47,
        "Scimitar": 0x48,
        "Way to the Dawn": 0x49,
        "Identity Disk": 0x4A,
        "Mage's Staff": 0x4B,
        "Unused 0x4C": 0x4C,
        "Unused 0x4D": 0x4D,
        "Protect Belt": 0x4E,
        "Gaia Belt": 0x4F,
        "Sword of the Ancestor (FAKE)": 0x50,
        "Kingdom Key D": 0x51,
        "Guard": 0x52,
        "Unused 0x53": 0x53,
        "Unused 0x54": 0x54,
        "Unused 0x55": 0x55,
        "Unused 0x56": 0x56,
        "Magnet Element": 0x57,
        "Reflect Element": 0x58,
        "Navigational Map": 0x59,
        "Castle Map": 0x5A,
        "Basement Map": 0x5B,
        "Castle Walls Map": 0x5C,
        "Unused 0x5D": 0x5D,
        "High Jump LV1": 0x5E,
        "High Jump LV2": 0x5F,
        "High Jump LV3": 0x60,
        "High Jump MAX": 0x61,
        "Quick Run LV1": 0x62,
        "Quick Run LV2": 0x63,
        "Quick Run LV3": 0x64,
        "Quick Run MAX": 0x65,
        "Aerial Dodge LV1": 0x66,
        "Aerial Dodge LV2": 0x67,
        "Aerial Dodge LV3": 0x68,
        "Aerial Dodge MAX": 0x69,
        "Glide LV1": 0x6A,
        "Glide LV2": 0x6B,
        "Glide LV3": 0x6C,
        "Glide MAX": 0x6D,
        "Unused 0x6E": 0x6E,
        "Cosmic Belt": 0x6F,
        "Encampment Area Map": 0x70,
        "Village Area Map": 0x71,
        "Cornerstone Hill Map": 0x72,
        "Window of Time Map 2": 0x73,
        "Lilliput Map": 0x74,
        "Building Site Map": 0x75,
        "Mickey's House Map": 0x76,
        "Disney Castle Map": 0x77,
        "Agrabah Map": 0x78,
        "Cave of Wonders Map": 0x79,
        "Ruins Map": 0x7A,
        "Undersea Kingdom Map": 0x7B,
        "Starry Hill": 0x7C,
        "100 Acre Wood Map": 0x7D,
        "Rabbit's Howse Map": 0x7E,
        "Piglet's Howse Map": 0x7F,
        "Kanga's Howse Map": 0x80,
        "Spooky Cave Map": 0x81,
        "Palace Map": 0x82,
        "Tent": 0x83,
        "Shock Charm": 0x84,
        "Shock Charm+": 0x85,
        "Coliseum Map": 0x86,
        "Underworld Map": 0x87,
        "Caverns Map": 0x88,
        "Upper Slash": 0x89,
        "Scan": 0x8A,
        "Adamant Shield": 0x8B,
        "Chain Gear": 0x8C,
        "Ogre Shield": 0x8D,
        "Falling Star": 0x8E,
        "Dreamcloud": 0x8F,
        "Knight Defender": 0x90,
        "Genji Shield": 0x91,
        "Akashic Record": 0x92,
        "Nobody Guard": 0x93,
        "Hammer Staff": 0x94,
        "Victory Bell": 0x95,
        "Meteor Staff": 0x96,
        "Comet Staff": 0x97,
        "Lord's Broom": 0x98,
        "Wisdom Wand": 0x99,
        "Rising Dragon": 0x9A,
        "Nobody Lance": 0x9B,
        "Shaman's Relic": 0x9C,
        "Grand Ribbon": 0x9D,
        "Aerial Recovery": 0x9E,
        "Lamp Charm": 0x9F,
        "Feather Charm": 0xA0,
        "Staff of Detection": 0xA1,
        "Combo Plus": 0xA2,
        "Air Combo Plus": 0xA3,
        "Unused 0xA4": 0xA4,
        "Donald Fire": 0xA5,
        "Donald Blizzard": 0xA6,
        "Donald Thunder": 0xA7,
        "Donald Cure": 0xA8,
        "Unused 0xA9": 0xA9,
        "Unused 0xAA": 0xAA,
        "Unused 0xAB": 0xAB,
        "Unused 0xAC": 0xAC,
        "Fire Bangle": 0xAD,
        "Fira Bangle": 0xAE,
        "Unused 0xAF": 0xAF,
        "Healing Water": 0xB0,
        "Furious Shout": 0xB1,
        "Unused 0xB2": 0xB2,
        "Unused 0xB3": 0xB3,
        "Unused 0xB4": 0xB4,
        "Unused 0xB5": 0xB5,
        "Unused 0xB6": 0xB6,
        "Unused 0xB7": 0xB7,
        "Unused 0xB8": 0xB8,
        "Unused 0xB9": 0xB9,
        "Unused 0xBA": 0xBA,
        "Cure Potion": 0xBB,
        "Unused 0xBC": 0xBC,
        "Unused 0xBD": 0xBD,
        "Healing Herb": 0xBE,
        "Unused 0xBF": 0xBF,
        "Unused 0xC0": 0xC0,
        "Unused 0xC1": 0xC1,
        "Unused 0xC2": 0xC2,
        "Slow 3": 0xC3,
        "Unused 0xC4": 0xC4,
        "Firaga Bangle": 0xC5,
        "Trinity Limit": 0xC6,
        "Fantasia": 0xC7,
        "Flare Force": 0xC8,
        "Tornado Fusion": 0xC9,
        "Teamwork": 0xCA,
        "Trick Fantasy": 0xCB,
        "Overdrive": 0xCC,
        "Howling Moon": 0xCD,
        "Applause, Applause": 0xCE,
        "Dragonblaze": 0xCF,
        "Eternal Session": 0xD0,
        "King's Pride": 0xD1,
        "Treasure Isle": 0xD2,
        "Complete Compilement": 0xD3,
        "Unused 0xD4": 0xD4,
        "Unused 0xD5": 0xD5,
        "Unused 0xD6": 0xD6,
        "Pulsing Thunder": 0xD7,
        "Brave Shot": 0xD8,
        "Brave Beat": 0xD9,
        "Sonic Strike": 0xDA,
        "Sonic End": 0xDB,
        "Wisdom Shot": 0xDC,
        "Mobile Action": 0xDD,
        "Unused 0xDE": 0xDE,
        "Synch Blade": 0xDF,
        "Magic Haste": 0xE0,
        "Magic Spice": 0xE1,
        "Secret Ansem Report 1": 0xE2,
        "Secret Ansem Report 2": 0xE3,
        "Secret Ansem Report 3": 0xE4,
        "Secret Ansem Report 4": 0xE5,
        "Secret Ansem Report 5": 0xE6,
        "Secret Ansem Report 6": 0xE7,
        "Secret Ansem Report 7": 0xE8,
        "Secret Ansem Report 8": 0xE9,
        "Secret Ansem Report 9": 0xEA,
        "Secret Ansem Report 10": 0xEB,
        "Secret Ansem Report 11": 0xEC,
        "Secret Ansem Report 12": 0xED,
        "Secret Ansem Report 13": 0xEE,
        "Unused 0xEF": 0xEF,
        "Unused 0xF0": 0xF0,
        "Unused 0xF1": 0xF1,
        "Unused 0xF2": 0xF2,
        "Unused 0xF3": 0xF3,
        "Unused 0xF4": 0xF4,
        "Unused 0xF5": 0xF5,
        "Over the Horizon": 0xF6,
        "Omega Finale": 0xF7,
        "Reflect Dummy": 0xF8,
        "Upper Dummy": 0xF9,
        "Halloween Town Map": 0xFA,
        "Naval Map": 0xFB,
        "Pride Rock Map": 0xFC,
        "Marketplace Map": 0xFD,
        "Pit Cell Area Map": 0xFE,
        "Twilight Town Map": 0xFF,
        "Dark City Map": 0x0100,
        "Master Strike": 0x0101,
        "Disaster": 0x0102,
        "Endless Magic": 0x0103,
        "Unused 0x0104": 0x0104,
        "Master Magic": 0x0105,
        "Slapshot": 0x0106,
        "Dodge Slash": 0x0107,
        "Slide Dash": 0x0108,
        "Guard Break": 0x0109,
        "Explosion": 0x010A,
        "Finishing Leap": 0x010B,
        "Counterguard": 0x010C,
        "Aerial Sweep": 0x010D,
        "Aerial Spiral": 0x010E,
        "Horizontal Slash": 0x010F,
        "Aerial Finish": 0x0110,
        "Retaliating Slash": 0x0111,
        "Drive Recovery": 0x0112,
        "High Drive Recovery": 0x0113,
        "Strength Boost": 0x0114,
        "Magic Boost": 0x0115,
        "Defense Boost": 0x0116,
        "AP Boost": 0x0117,
        "Dark Shard": 0x0118,
        "Dark Stone": 0x0119,
        "Dark Gem": 0x011A,
        "Dark Crystal": 0x011B,
        "Firagun Bangle": 0x011C,
        "Unused 0x011D": 0x011D,
        "Blizzard Armlet": 0x011E,
        "Blizzara Armlet": 0x011F,
        "Blizzaga Armlet": 0x0120,
        "Blizzagun Armlet": 0x0121,
        "Unused 0x0122": 0x0122,
        "Thunder Trinket": 0x0123,
        "Thundara Trinket": 0x0124,
        "Thundaga Trinket": 0x0125,
        "Thundagun Trinket": 0x0126,
        "Unused 0x0127": 0x0127,
        "Shadow Anklet": 0x0128,
        "Dark Anklet": 0x0129,
        "Midnight Anklet": 0x012A,
        "Chaos Anklet": 0x012B,
        "Unused 0x012C": 0x012C,
        "Abas Chain": 0x012D,
        "Aegis Chain": 0x012E,
        "Acrisius": 0x012F,
        "Ribbon": 0x0130,
        "Champion Belt": 0x0131,
        "Petite Ribbon": 0x0132,
        "Acrisius+": 0x0133,
        "Cosmic Chain": 0x0134,
        "Unused 0x0135": 0x0135,
        "Unused 0x0136": 0x0136,
        "Unused 0x0137": 0x0137,
        "Unused 0x0138": 0x0138,
        "Unused 0x0139": 0x0139,
        "Unused 0x013A": 0x013A,
        "Unused 0x013B": 0x013B,
        "Unused 0x013C": 0x013C,
        "Blazing Shard": 0x013D,
        "Blazing Stone": 0x013E,
        "Blazing Gem": 0x013F,
        "Blazing Crystal": 0x0140,
        "Unused 0x0141": 0x0141,
        "Unused 0x0142": 0x0142,
        "Unused 0x0143": 0x0143,
        "Unused 0x0144": 0x0144,
        "Lightning Shard": 0x0145,
        "Lightning Stone": 0x0146,
        "Lightning Gem": 0x0147,
        "Lightning Crystal": 0x0148,
        "Power Shard": 0x0149,
        "Power Stone": 0x014A,
        "Power Gem": 0x014B,
        "Power Crystal": 0x014C,
        "Lucid Shard": 0x014D,
        "Lucid Stone": 0x014E,
        "Lucid Gem": 0x014F,
        "Lucid Crystal": 0x0150,
        "Dense Shard": 0x0151,
        "Dense Stone": 0x0152,
        "Dense Gem": 0x0153,
        "Dense Crystal": 0x0154,
        "Twilight Shard": 0x0155,
        "Twilight Stone": 0x0156,
        "Twilight Gem": 0x0157,
        "Twilight Crystal": 0x0158,
        "Mythril Shard": 0x0159,
        "Mythril Stone": 0x015A,
        "Mythril Gem": 0x015B,
        "Mythril Crystal": 0x015C,
        "Bright Shard": 0x015D,
        "Bright Stone": 0x015E,
        "Bright Gem": 0x015F,
        "Bright Crystal": 0x0160,
        "Energy Shard": 0x0161,
        "Energy Stone": 0x0162,
        "Energy Gem": 0x0163,
        "Energy Crystal": 0x0164,
        "Serenity Shard": 0x0165,
        "Serenity Stone": 0x0166,
        "Serenity Gem": 0x0167,
        "Serenity Crystal": 0x0168,
        "Orichalcum+": 0x0169,
        "Munny Pouch": 0x016A,
        "Crystal Orb": 0x016B,
        "Seifer's Trophy": 0x016C,
        "Tournament Poster": 0x016D,
        "Poster": 0x016E,
        "Letter": 0x016F,
        "Naminé's Sketches": 0x0170,
        "Membership Card": 0x0171,
        "Olympus Stone": 0x0172,
        "Auron's Statue": 0x0173,
        "Cursed Medallion": 0x0174,
        "Present": 0x0175,
        "Decoy Presents": 0x0176,
        "Ice Cream": 0x0177,
        "Picture": 0x0178,
        "Orichalcum": 0x0179,
        "Frost Shard": 0x017A,
        "Frost Stone": 0x017B,
        "Frost Gem": 0x017C,
        "Frost Crystal": 0x017D,
        "Mega-Recipe": 0x017E,
        "Baseball Charm": 0x017F,
        "Struggle Sword": 0x0180,
        "Auto Valor": 0x0181,
        "Auto Wisdom": 0x0182,
        "Auto Master": 0x0183,
        "Auto Final": 0x0184,
        "Auto Summon": 0x0185,
        "Combo Boost": 0x0186,
        "Air Combo Boost": 0x0187,
        "Reaction Boost": 0x0188,
        "Finishing Plus": 0x0189,
        "Negative Combo": 0x018A,
        "Berserk Charge": 0x018B,
        "Damage Drive": 0x018C,
        "Drive Boost": 0x018D,
        "Form Boost": 0x018E,
        "Summon Boost": 0x018F,
        "Combination Boost": 0x0190,
        "Experience Boost": 0x0191,
        "Leaf Bracer": 0x0192,
        "Magic Lock-On": 0x0193,
        "No Experience": 0x0194,
        "Draw": 0x0195,
        "Jackpot": 0x0196,
        "Lucky Lucky": 0x0197,
        "Fire Boost": 0x0198,
        "Blizzard Boost": 0x0199,
        "Thunder Boost": 0x019A,
        "Item Boost": 0x019B,
        "MP Rage": 0x019C,
        "MP Haste": 0x019D,
        "Defender": 0x019E,
        "Second Chance": 0x019F,
        "Once More": 0x01A0,
        "Auto Limit": 0x01A1,
        "Auto Change": 0x01A2,
        "Hyper Healing": 0x01A3,
        "Auto Healing": 0x01A4,
        "MP Hastera": 0x01A5,
        "MP Hastega": 0x01A6,
        "Goofy Tornado": 0x01A7,
        "Unused 0x01A8": 0x01A8,
        "Goofy Turbo": 0x01A9,
        "Slash Frenzy": 0x01AA,
        "Quickplay": 0x01AB,
        "Divider": 0x01AC,
        "Goofy Bash": 0x01AD,
        "Ferocious Rush": 0x01AE,
        "Blazing Fury": 0x01AF,
        "Icy Terror": 0x01B0,
        "Bolts of Sorrow": 0x01B1,
        "Mushu Fire": 0x01B2,
        "Flametongue": 0x01B3,
        "Dark Shield": 0x01B4,
        "Unused 0x01B5": 0x01B5,
        "Dark Aura": 0x01B6,
        "Fierce Claw": 0x01B7,
        "Groundshaker": 0x01B8,
        "Unused 0x01B9": 0x01B9,
        "Unused 0x01BA": 0x01BA,
        "Unused 0x01BB": 0x01BB,
        "Scouting Disk": 0x01BC,
        "Slow 2": 0x01BD,
        "No Mercy": 0x01BE,
        "Rain Storm": 0x01BF,
        "Bone Smash": 0x01C0,
        "Star Recipe": 0x01C1,
        "Recovery Recipe": 0x01C2,
        "Skill Recipe": 0x01C3,
        "Guard Recipe": 0x01C4,
        "Dummy 06": 0x01C5,
        "Dummy 07": 0x01C6,
        "Dummy 08": 0x01C7,
        "Dummy 09": 0x01C8,
        "Dummy 10": 0x01C9,
        "Dummy 11": 0x01CA,
        "Dummy 12": 0x01CB,
        "Dummy 13": 0x01CC,
        "Dummy 14": 0x01CD,
        "Dummy 15": 0x01CE,
        "Dummy 16": 0x01CF,
        "Road to Discovery": 0x01D0,
        "Strength Beyond Strength": 0x01D1,
        "Book of Shadows": 0x01D2,
        "Cloaked Thunder": 0x01D3,
        "Eternal Blossom": 0x01D4,
        "Rare Document": 0x01D5,
        "Dummy 23": 0x01D6,
        "Dummy 24": 0x01D7,
        "Dummy 25": 0x01D8,
        "Dummy 26": 0x01D9,
        "Dummy 27": 0x01DA,
        "Style Recipe": 0x01DB,
        "Moon Recipe": 0x01DC,
        "Queen Recipe": 0x01DD,
        "King Recipe": 0x01DE,
        "Ultimate Recipe": 0x01DF,
        "Star Seeker": 0x01E0,
        "Hidden Dragon": 0x01E1,
        "Save the Queen": 0x01E2,
        "Save the King": 0x01E3,
        "Hero's Crest": 0x01E4,
        "Monochrome": 0x01E5,
        "Follow the Wind": 0x01E6,
        "Circle of Life": 0x01E7,
        "Photon Debugger": 0x01E8,
        "Gull Wing": 0x01E9,
        "Rumbling Rose": 0x01EA,
        "Guardian Soul": 0x01EB,
        "Wishing Lamp": 0x01EC,
        "Decisive Pumpkin": 0x01ED,
        "Sleeping Lion": 0x01EE,
        "Sweet Memories": 0x01EF,
        "Mysterious Abyss": 0x01F0,
        "Fatal Crest": 0x01F1,
        "Bond of Flame": 0x01F2,
        "Fenrir": 0x01F3,
        "Ultima Weapon": 0x01F4,
        "Struggle Wand": 0x01F5,
        "Struggle Hammer": 0x01F6,
        "Save the Queen+": 0x01F7,
        "Save the King+": 0x01F8,
        "The Interceptor Map": 0x01F9,
        "The Black Pearl Map": 0x01FA,
        "Isla de Muerta Map": 0x01FB,
        "Ship Graveyard Map": 0x01FC,
        "Christmas Town Map": 0x01FD,
        "Curly Hill Map": 0x01FE,
        "Oasis Map": 0x01FF,
        "Savannah Map": 0x0200,
        "Castle Perimeter Map": 0x0201,
        "The Great Maw Map": 0x0202,
        "I/O Tower Map": 0x0203,
        "Central Computer Core Map": 0x0204,
        "Solar Sailer Simulation Map": 0x0205,
        "Window of Time Map": 0x0206,
        "Auto Assault": 0x0207,
        "Finishing Blast": 0x0208,
        "Combo Upper": 0x0209,
        "Aerial Impulse": 0x020A,
        "Retaliating Smash": 0x020B,
        "Promise Charm": 0x020C,
        "Running Tackle": 0x020D,
        "Dash": 0x020E,
        "Final Arcana": 0x020F,
        "Final Strike": 0x0210,
        "Final Arts": 0x0211,
        "Crime & Punishment": 0x0212,
        "Sunset Hill Map": 0x0213,
        "Mansion Map": 0x0214,
        "Tower Map": 0x0215,
        "DH Map": 0x0216,
        "Munny Pouch": 0x0217,
        "Castle That Never Was Map": 0x0218,
        "Hades Cup Trophy": 0x0219,
        "The Struggle Trophy": 0x021A,
        "Combo Master": 0x021B,
        "Drive Converter": 0x021C,
        "Light & Darkness": 0x021D,
        "Damage Control": 0x021E,
        "Two Become One": 0x021F,
        "Winner's Proof": 0x0220,
        "Centurion": 0x0221,
        "Centurion+": 0x0222,
        "Plain Mushroom": 0x0223,
        "Plain Mushroom+": 0x0224,
        "Precious Mushroom": 0x0225,
        "Precious Mushroom+": 0x0226,
        "Premium Mushroom": 0x0227,
        "Frozen Pride": 0x0228,
        "Frozen Pride+": 0x0229,
        "Joyous Mushroom": 0x022A,
        "Joyous Mushroom+": 0x022B,
        "Majestic Mushroom": 0x022C,
        "Majestic Mushroom+": 0x022D,
        "Ultimate Mushroom": 0x022E,
        "Flash Step": 0x022F,
        "Aerial Dive": 0x0230,
        "Magnet Burst": 0x0231,
        "Vicinity Break": 0x0232,
        "Limit Form": 0x0233,
        "Dodge Roll LV 1": 0x0234,
        "Dodge Roll LV 2": 0x0235,
        "Dodge Roll LV 3": 0x0236,
        "Dodge Roll MAX": 0x0237,
        "Auto Limit Form": 0x0238,
        "Sonic Blade": 0x0239,
        "Ars Arcanum": 0x023A,
        "Strike Raid": 0x023B,
        "Ragnarok": 0x023C,
        "Zantetsuken": 0x023D,
        "Ripple Drive": 0x023E,
        "Hurricane Period": 0x023F,
        "Remembrance Shard": 0x0240,
        "Remembrance Stone": 0x0241,
        "Remembrance Gem": 0x0242,
        "Remembrance Crystal": 0x0243,
        "Tranquility Shard": 0x0244,
        "Tranquility Stone": 0x0245,
        "Tranquility Gem": 0x0246,
        "Tranquility Crystal": 0x0247,
        "Lost Illusion": 0x0248,
        "Manifest Illusion": 0x0249,
        "Dark Remembrance Map": 0x024A,
        "Zantetsu Counter": 0x024B,
        "Reflect Combo": 0x024C,
        "HP Gain": 0x024D,
        "Depths of Remembrance Map": 0x024E,
        "Unused 0x024F": 0x024F,
        "Garden of Assemblage Map": 0x0250,
        "Proof of Connection": 0x0251,
        "Proof of Nonexistence": 0x0252,
        "Proof of Peace": 0x0253,
        "Protect": 0x0254,
        "Protectra": 0x0255,
        "Protectga": 0x0256,
        "Executive's Ring": 0x0257,
        "Shaman's Relic+": 0x0258,
        "Akashic Record+": 0x0259,
    }
    obj.weapon_dict = {
        "Sora": [
            "Empty",
            "Kingdom Key",
            "Oathkeeper",
            "Oblivion",
            "Star Seeker",
            "Hidden Dragon",
            "Hero's Crest",
            "Monochrome",
            "Follow the Wind",
            "Circle of Life",
            "Photon Debugger",
            "Gull Wing",
            "Rumbling Rose",
            "Guardian Soul",
            "Wishing Lamp",
            "Decisive Pumpkin",
            "Sleeping Lion",
            "Sweet Memories",
            "Mysterious Abyss",
            "Fatal Crest",
            "Bond of Flame",
            "Fenrir",
            "Ultima Weapon",
            "Two Become One",
            "Winner's Proof",
            "Struggle Sword",
            "Struggle Wand",
            "Struggle Hammer",
            "Detection Saber",
            "Edge/Frontier of Ultima",
            "Antiform Dummy",
        ],
        "Donald": [
            "Empty",
            "Mage's Staff",
            "Hammer Staff",
            "Victory Bell",
            "Meteor Staff",
            "Comet Staff",
            "Lord's Broom",
            "Wisdom Wand",
            "Rising Dragon",
            "Nobody Lance",
            "Shaman's Relic",
            "Shaman's Relic+",
            "Save the Queen",
            "Save the Queen+",
            "Centurion",
            "Centurion+",
            "Plain Mushroom",
            "Plain Mushroom+",
            "Precious Mushroom",
            "Precious Mushroom+",
            "Premium Mushroom",
            "Staff of Detection",
        ],
        "Goofy": [
            "Empty",
            "Knight's Shield",
            "Adamant Shield",
            "Chain Gear",
            "Ogre Shield",
            "Falling Star",
            "Dreamcloud",
            "Knight Defender",
            "Genji Shield",
            "Akashic Record",
            "Akashic Record+",
            "Nobody Guard",
            "Save the King",
            "Save the King+",
            "Frozen Pride",
            "Frozen Pride+",
            "Joyous Mushroom",
            "Joyous Mushroom+",
            "Majestic Mushroom",
            "Majestic Mushroom+",
            "Ultimate Mushroom",
            "Detection Shield",
            "Test the King",
        ],
        "Guest": [
            "Empty",
            "Kingdom Key D",
            "Battlefields of War",
            "Sword of the Ancestor",
            "Sword of the Ancestor (FAKE)",
            "Beast's Claw",
            "Bone Fist",
            "Proud Fang",
            "Skill and Crossbones",
            "Scimitar",
            "Identity Disk",
            "Way to the Dawn",
        ]
    }
    obj.armor_list = [
        "Empty",
        "Elven Bandanna",
        "Divine Bandanna",
        "Protect Belt",
        "Gaia Belt",
        "Power Band",
        "Buster Band",
        "Cosmic Belt",
        "Fire Bangle",
        "Fira Bangle",
        "Firaga Bangle",
        "Firagun Bangle",
        "Blizzard Armlet",
        "Blizzara Armlet",
        "Blizzaga Armlet",
        "Blizzagun Armlet",
        "Thunder Trinket",
        "Thundara Trinket",
        "Thundaga Trinket",
        "Thundagun Trinket",
        "Shock Charm",
        "Shock Charm+",
        "Shadow Anklet",
        "Dark Anklet",
        "Midnight Anklet",
        "Chaos Anklet",
        "Champion Belt",
        "Abas Chain",
        "Aegis Chain",
        "Acrisius",
        "Acrisius+",
        "Cosmic Chain",
        "Petite Ribbon",
        "Ribbon",
        "Grand Ribbon",
    ]
    obj.accessory_list = [
        "Empty",
        "Ability Ring",
        "Engineer's Ring",
        "Technician's Ring",
        "Skill Ring",
        "Skillful Ring",
        "Expert's Ring",
        "Master's Ring",
        "Cosmic Ring",
        "Executive's Ring",
        "Sardonyx Ring",
        "Tourmaline Ring",
        "Aquamarine Ring",
        "Garnet Ring",
        "Diamond Ring",
        "Silver Ring",
        "Gold Ring",
        "Platinum Ring",
        "Mythril Ring",
        "Orichalcum Ring",
        "Soldier Earring",
        "Fencer Earring",
        "Mage Earring",
        "Slayer Earring",
        "Medal",
        "Moon Amulet",
        "Star Charm",
        "Cosmic Arts",
        "Shadow Archive",
        "Shadow Archive+",
        "Full Bloom",
        "Full Bloom+",
        "Draw Ring",
        "Lucky Ring",
    ]
    obj.ability_list = [
        "Empty",
        "Aerial Dive",
        "Aerial Dodge LV1",
        "Aerial Dodge LV2",
        "Aerial Dodge LV3",
        "Aerial Dodge MAX",
        "Aerial Finish",
        "Aerial Impulse",
        "Aerial Recovery",
        "Aerial Spiral",
        "Aerial Sweep",
        "Air Combo Boost",
        "Air Combo Plus",
        "Applause, Applause",
        "Ars Arcanum",
        "Auto Assault",
        "Auto Change",
        "Auto Final",
        "Auto Healing",
        "Auto Limit",
        "Auto Limit Form",
        "Auto Master",
        "Auto Summon",
        "Auto Valor",
        "Auto Wisdom",
        "Berserk Charge",
        "Blazing Fury",
        "Blizzard Boost",
        "Bolts of Sorrow",
        "Bone Smash",
        "Brave Beat",
        "Brave Shot",
        "Combo Boost",
        "Combo Master",
        "Combo Plus",
        "Combo Upper",
        "Combination Boost",
        "Complete Compilement",
        "Counterguard",
        "Crime & Punishment",
        "Cure Potion",
        "Damage Control",
        "Damage Drive",
        "Dark Aura",
        "Dark Shield",
        "Dash",
        "Defender",
        "Disaster",
        "Divider",
        "Dodge Roll LV 1",
        "Dodge Roll LV 2",
        "Dodge Roll LV 3",
        "Dodge Roll MAX",
        "Dodge Slash",
        "Donald Blizzard",
        "Donald Cure",
        "Donald Fire",
        "Donald Thunder",
        "Draw",
        "Drive Boost",
        "Drive Converter",
        "Dragonblaze",
        "Endless Magic",
        "Eternal Session",
        "Explosion",
        "Experience Boost",
        "Fantasia",
        "Ferocious Rush",
        "Final Arcana",
        "Final Arts",
        "Final Strike",
        "Finishing Blast",
        "Finishing Leap",
        "Finishing Plus",
        "Fire Boost",
        "Firaga Bangle",
        "Fierce Claw",
        "Flash Step",
        "Flametongue",
        "Flare Force",
        "Form Boost",
        "Furious Shout",
        "Glide LV1",
        "Glide LV2",
        "Glide LV3",
        "Glide MAX",
        "Goofy Bash",
        "Goofy Tornado",
        "Goofy Turbo",
        "Groundshaker",
        "Guard",
        "Guard Break",
        "Healing Herb",
        "Healing Water",
        "High Jump LV1",
        "High Jump LV2",
        "High Jump LV3",
        "High Jump MAX",
        "Horizontal Slash",
        "Howling Moon",
        "Hurricane Period",
        "HP Gain",
        "Hyper Healing",
        "Icy Terror",
        "Item Boost",
        "Jackpot",
        "King's Pride",
        "Leaf Bracer",
        "Light & Darkness",
        "Lucky Lucky",
        "Magic Haste",
        "Magic Lock-On",
        "Magic Spice",
        "Magnet Burst",
        "Master Magic",
        "Master Strike",
        "Mobile Action",
        "MP Haste",
        "MP Hastega",
        "MP Hastera",
        "MP Rage",
        "Mushu Fire",
        "Negative Combo",
        "No Experience",
        "No Mercy",
        "Omega Finale",
        "Once More",
        "Over the Horizon",
        "Overdrive",
        "Pulsing Thunder",
        "Protect",
        "Protectga",
        "Protectra",
        "Quick Run LV1",
        "Quick Run LV2",
        "Quick Run LV3",
        "Quick Run MAX",
        "Quickplay",
        "Rain Storm",
        "Ragnarok",
        "Reaction Boost",
        "Reflect Combo",
        "Reflect Dummy",
        "Retaliating Slash",
        "Retaliating Smash",
        "Ripple Drive",
        "Running Tackle",
        "Scan",
        "Scouting Disk",
        "Second Chance",
        "Slash Frenzy",
        "Slapshot",
        "Slide Dash",
        "Slow 2",
        "Slow 3",
        "Sonic Blade",
        "Sonic End",
        "Sonic Strike",
        "Strike Raid",
        "Summon Boost",
        "Synch Blade",
        "Teamwork",
        "Thunder Boost",
        "Tornado Fusion",
        "Treasure Isle",
        "Trick Fantasy",
        "Trinity Limit",
        "Upper Dummy",
        "Upper Slash",
        "Vicinity Break",
        "Wisdom Shot",
        "Zantetsu Counter",
        "Zantetsuken",
    ]
    obj.inventory_dict = {
        "Potion": 0x00,
        "Hi-Potion": 0x01,
        "Ether": 0x02,
        "Elixir": 0x03,
        "Mega-Potion": 0x04,
        "Mega-Ether": 0x05,
        "Megalixir": 0x06,
        "Ability Ring": 0x07,
        "Engineer's Ring": 0x08,
        "Technician's Ring": 0x09,
        "Expert's Ring": 0x0A,
        "Sardonyx Ring": 0x0B,
        "Tourmaline Ring": 0x0C,
        "Aquamarine Ring": 0x0D,
        "Garnet Ring": 0x0E,
        "Diamond Ring": 0x0F,
        "Silver Ring": 0x10,
        "Gold Ring": 0x11,
        "Platinum Ring": 0x12,
        "Mythril Ring": 0x13,
        "Fire Element": 0x14,
        "Blizzard Element": 0x15,
        "Thunder Element": 0x16,
        "Cure Element": 0x17,
        "Torn Pages": 0x18,
        "Unused 0x19": 0x19,
        "Orichalcum Ring": 0x1A,
        "Master's Ring": 0x1B,
        "Moon Amulet": 0x1C,
        "Unused 0x1D": 0x1D,
        "Star Charm": 0x1E,
        "Skill Ring": 0x1F,
        "Skillful Ring": 0x20,
        "Kingdom Key": 0x21,
        "Oathkeeper": 0x22,
        "Oblivion": 0x23,
        "Detection Saber": 0x24,
        "Edge/Frontier of Ultima": 0x25,
        "Soldier Earring": 0x26,
        "Fencer Earring": 0x27,
        "Mage Earring": 0x28,
        "Knight's Shield": 0x29,
        "Detection Shield": 0x2A,
        "Test the King": 0x2B,
        "Slayer Earring": 0x2C,
        "Cosmic Ring": 0x2D,
        "Battlefields of War": 0x2E,
        "Sword of the Ancestor": 0x2F,
        "Medal": 0x30,
        "Cosmic Arts": 0x31,
        "Shadow Archive": 0x32,
        "Beast's Claw": 0x33,
        "Bone Fist": 0x34,
        "Proud Fang": 0x35,
        "Skill and Crossbones": 0x36,
        "Shadow Archive+": 0x37,
        "Lucky Ring": 0x38,
        "Full Bloom": 0x39,
        "Draw Ring": 0x3A,
        "Full Bloom+": 0x3B,
        "Elven Bandanna": 0x3C,
        "Divine Bandanna": 0x3D,
        "Power Band": 0x3E,
        "Antiform Dummy": 0x3F,
        "Scimitar": 0x40,
        "Way to the Dawn": 0x41,
        "Identity Disk": 0x42,
        "Mage's Staff": 0x43,
        "Unused 0x44": 0x44,
        "Unused 0x45": 0x45,
        "Buster Band": 0x46,
        "Protect Belt": 0x47,
        "Sword of the Ancestor (FAKE)": 0x48,
        "Kingdom Key D": 0x49,
        "Gaia Belt": 0x4A,
        "Unused 0x4B": 0x4B,
        "Unused 0x4C": 0x4C,
        "Unused 0x4D": 0x4D,
        "Unused 0x4E": 0x4E,
        "Magnet Element": 0x4F,
        "Reflect Element": 0x50,
        "Cosmic Belt": 0x51,
        "Shock Charm": 0x52,
        "Shock Charm+": 0x53,
        "Grand Ribbon": 0x54,
        "Unused 0x55": 0x55,
        "Unused 0x56": 0x56,
        "Fire Bangle": 0x57,
        "Fira Bangle": 0x58,
        "Firaga Bangle": 0x59,
        "Firagun Bangle": 0x5A,
        "Unused 0x5B": 0x5B,
        "Blizzard Armlet": 0x5C,
        "Blizzara Armlet": 0x5D,
        "Blizzaga Armlet": 0x5E,
        "Blizzagun Armlet": 0x5F,
        "Unused 0x60": 0x60,
        "Tent": 0x61,
        "Thunder Trinket": 0x62,
        "Thundara Trinket": 0x63,
        "Thundaga Trinket": 0x64,
        "Thundagun Trinket": 0x65,
        "Adamant Shield": 0x66,
        "Chain Gear": 0x67,
        "Ogre Shield": 0x68,
        "Falling Star": 0x69,
        "Dreamcloud": 0x6A,
        "Knight Defender": 0x6B,
        "Genji Shield": 0x6C,
        "Akashic Record": 0x6D,
        "Nobody Guard": 0x6E,
        "Hammer Staff": 0x6F,
        "Victory Bell": 0x70,
        "Meteor Staff": 0x71,
        "Comet Staff": 0x72,
        "Lord's Broom": 0x73,
        "Wisdom Wand": 0x74,
        "Rising Dragon": 0x75,
        "Nobody Lance": 0x76,
        "Shaman's Relic": 0x77,
        "Unused 0x78": 0x78,
        "Shadow Anklet": 0x79,
        "Staff of Detection": 0x7A,
        "Dark Anklet": 0x7B,
        "Midnight Anklet": 0x7C,
        "Chaos Anklet": 0x7D,
        "Unused 0x7E": 0x7E,
        "Abas Chain": 0x7F,
        "Aegis Chain": 0x80,
        "Acrisius": 0x81,
        "Ribbon": 0x82,
        "Champion Belt": 0x83,
        "Petite Ribbon": 0x84,
        "Acrisius+": 0x85,
        "Cosmic Chain": 0x86,
        "Unused 0x87": 0x87,
        "Unused 0x88": 0x88,
        "Unused 0x89": 0x89,
        "Unused 0x8A": 0x8A,
        "Unused 0x8B": 0x8B,
        "Unused 0x8C": 0x8C,
        "Unused 0x8D": 0x8D,
        "Unused 0x8E": 0x8E,
        "Blazing Shard": 0x8F,
        "Blazing Stone": 0x90,
        "Blazing Gem": 0x91,
        "Blazing Crystal": 0x92,
        "Unused 0x93": 0x93,
        "Unused 0x94": 0x94,
        "Unused 0x95": 0x95,
        "Unused 0x96": 0x96,
        "Lightning Shard": 0x97,
        "Lightning Stone": 0x98,
        "Lightning Gem": 0x99,
        "Lightning Crystal": 0x9A,
        "Power Shard": 0x9B,
        "Power Stone": 0x9C,
        "Power Gem": 0x9D,
        "Power Crystal": 0x9E,
        "Lucid Shard": 0x9F,
        "Lucid Stone": 0xA0,
        "Lucid Gem": 0xA1,
        "Lucid Crystal": 0xA2,
        "Dense Shard": 0xA3,
        "Dense Stone": 0xA4,
        "Dense Gem": 0xA5,
        "Dense Crystal": 0xA6,
        "Twilight Shard": 0xA7,
        "Twilight Stone": 0xA8,
        "Twilight Gem": 0xA9,
        "Twilight Crystal": 0xAA,
        "Mythril Shard": 0xAB,
        "Mythril Stone": 0xAC,
        "Mythril Gem": 0xAD,
        "Mythril Crystal": 0xAE,
        "Bright Shard": 0xAF,
        "Bright Stone": 0xB0,
        "Bright Gem": 0xB1,
        "Bright Crystal": 0xB2,
        "Energy Shard": 0xB3,
        "Energy Stone": 0xB4,
        "Energy Gem": 0xB5,
        "Energy Crystal": 0xB6,
        "Serenity Shard": 0xB7,
        "Serenity Stone": 0xB8,
        "Serenity Gem": 0xB9,
        "Serenity Crystal": 0xBA,
        "Orichalcum+": 0xBB,
        "Munny Pouch": 0xBC,
        "Crystal Orb": 0xBD,
        "Seifer's Trophy": 0xBE,
        "Tournament Poster": 0xBF,
        "Poster": 0xC0,
        "Letter": 0xC1,
        "Naminé's Sketches": 0xC2,
        "Membership Card": 0xC3,
        "Olympus Stone": 0xC4,
        "Auron's Statue": 0xC5,
        "Cursed Medallion": 0xC6,
        "Present": 0xC7,
        "Decoy Presents": 0xC8,
        "Ice Cream": 0xC9,
        "Picture": 0xCA,
        "Orichalcum": 0xCB,
        "Frost Shard": 0xCC,
        "Frost Stone": 0xCD,
        "Frost Gem": 0xCE,
        "Frost Crystal": 0xCF,
        "Mega-Recipe": 0xD0,
        "Struggle Sword": 0xD1,
        "Star Recipe": 0xD2,
        "Recovery Recipe": 0xD3,
        "Skill Recipe": 0xD4,
        "Guard Recipe": 0xD5,
        "Dummy 06": 0xD6,
        "Dummy 07": 0xD7,
        "Dummy 08": 0xD8,
        "Dummy 09": 0xD9,
        "Dummy 10": 0xDA,
        "Dummy 11": 0xDB,
        "Dummy 12": 0xDC,
        "Dummy 13": 0xDD,
        "Dummy 14": 0xDE,
        "Dummy 15": 0xDF,
        "Dummy 16": 0xE0,
        "Road to Discovery": 0xE1,
        "Strength Beyond Strength": 0xE2,
        "Book of Shadows": 0xE3,
        "Drive Recovery": 0xE4,
        "High Drive Recovery": 0xE5,
        "Strength Boost": 0xE6,
        "Magic Boost": 0xE7,
        "Defense Boost": 0xE8,
        "AP Boost": 0xE9,
        "Dark Shard": 0xEA,
        "Dark Stone": 0xEB,
        "Dark Gem": 0xEC,
        "Dark Crystal": 0xED,
        "Cloaked Thunder": 0xEE,
        "Eternal Blossom": 0xEF,
        "Rare Document": 0xF0,
        "Dummy 23": 0xF1,
        "Dummy 24": 0xF2,
        "Dummy 25": 0xF3,
        "Dummy 26": 0xF4,
        "Dummy 27": 0xF5,
        "Style Recipe": 0xF6,
        "Moon Recipe": 0xF7,
        "Queen Recipe": 0xF8,
        "King Recipe": 0xF9,
        "Ultimate Recipe": 0xFA,
        "Star Seeker": 0xFB,
        "Hidden Dragon": 0xFC,
        "Save the Queen": 0xFD,
        "Save the King": 0xFE,
        "Hero's Crest": 0xFF,
        "Monochrome": 0x0100,
        "Follow the Wind": 0x0101,
        "Circle of Life": 0x0102,
        "Photon Debugger": 0x0103,
        "Gull Wing": 0x0104,
        "Rumbling Rose": 0x0105,
        "Guardian Soul": 0x0106,
        "Wishing Lamp": 0x0107,
        "Decisive Pumpkin": 0x0108,
        "Sleeping Lion": 0x0109,
        "Sweet Memories": 0x010A,
        "Mysterious Abyss": 0x010B,
        "Fatal Crest": 0x010C,
        "Bond of Flame": 0x010D,
        "Fenrir": 0x010E,
        "Ultima Weapon": 0x010F,
        "Struggle Wand": 0x0110,
        "Struggle Hammer": 0x0111,
        "Save the Queen+": 0x0112,
        "Save the King+": 0x0113,
        "Promise Charm": 0x0114,
        "Munny Pouch": 0x0115,
        "Hades Cup Trophy": 0x0116,
        "\"The Struggle\" Trophy": 0x0117,
        // Start of FM exclusive IDs
        "Two Become One": 0x0118,
        "Winner's Proof": 0x0119,
        "Centurion": 0x011A,
        "Centurion+": 0x011B,
        "Plain Mushroom": 0x011C,
        "Plain Mushroom+": 0x011D,
        "Precious Mushroom": 0x011E,
        "Precious Mushroom+": 0x011F,
        "Premium Mushroom": 0x0120,
        "Frozen Pride": 0x0121,
        "Frozen Pride+": 0x0122,
        "Joyous Mushroom": 0x0123,
        "Joyous Mushroom+": 0x0124,
        "Majestic Mushroom": 0x0125,
        "Majestic Mushroom+": 0x0126,
        "Ultimate Mushroom": 0x0127,
        "Remembrance Shard": 0x0128,
        "Remembrance Stone": 0x0129,
        "Remembrance Gem": 0x012A,
        "Remembrance Crystal": 0x012B,
        "Tranquility Shard": 0x012C,
        "Tranquility Stone": 0x012D,
        "Tranquility Gem": 0x012E,
        "Tranquility Crystal": 0x012F,
        "Lost Illusion": 0x0130,
        "Manifest Illusion": 0x0131,
        "Proof of Connection": 0x0132,
        "Proof of Nonexistence": 0x0133,
        "Proof of Peace": 0x0134,
        "Executive's Ring": 0x0135,
        "Shaman's Relic+": 0x0136,
        "Akashic Record+": 0x0137,
    }
}
