minigame_list = [
    "Pain and Panic Cup",
    "Cerberus Cup",
    "Titan Cup",
    "Goddess of Fate Cup",
    "Pain and Panic Paradox Cup",
    "Cerberus Paradox Cup",
    "Titan Paradox Cup",
    "Hades Paradox Cup",
    "Phil's Training",
    "Gift Wrapping",
    "Light Cycle",
    "Poster Duty",
    "Cargo Climb",
    "Bumble Buster",
    "Mail Delivery",
    "Grandstander",
    "Junk Sweep",
    "A Blustery Rescue",
    "Hunny Slider",
    "Balloon Bounce",
    "SB Sand Slider",
    "SB Time Attack",
    "SB Freestyle",
    "SB Workshop Rave",
    "SB Street Rave",
    "The Hunny Pot",
    "The Expotition",
    "Magic Carpet",
    "Mushroom XIII: No. 1",
    "Mushroom XIII: No. 2",
    "Mushroom XIII: No. 3",
    "Mushroom XIII: No. 4",
    "Mushroom XIII: No. 5",
    "Mushroom XIII: No. 6",
    "Mushroom XIII: No. 7",
    "Mushroom XIII: No. 8",
    "Mushroom XIII: No. 9",
    "Mushroom XIII: No. 10",
    "Mushroom XIII: No. 11",
    "Mushroom XIII: No. 12",
]
