def inventory_dicts(obj):
    obj.item1_dict = {
        "Empty": 0x00,
        "Potion": 0x01,
        "Hi-Potion": 0x02,
        "Ether": 0x03,
        "Elixir": 0x04,
        "Unused 0x05": 0x05,
        "Mega-Potion": 0x06,
        "Mega-Ether": 0x07,
        "Megalixir": 0x08,
        "Fury Stone": 0x09,
        "Power Stone": 0x0A,
        "Energy Stone": 0x0B,
        "Blazing Stone": 0x0C,
        "Frost Stone": 0x0D,
        "Lightning Stone": 0x0E,
        "Dazzling Stone": 0x0F,
        "Stormy Stone": 0x10
    }
    obj.accessory_dict =  {
        "Empty": 0x00,
        "Protect Chain": 0x11,
        "Protera Chain": 0x12,
        "Protega Chain": 0x13,
        "Fire Ring": 0x14,
        "Fira Ring": 0x15,
        "Firaga Ring": 0x16,
        "Blizzard Ring": 0x17,
        "Blizzara Ring": 0x18,
        "Blizzaga Ring": 0x19,
        "Thunder Ring": 0x1A,
        "Thundara Ring": 0x1B,
        "Thundaga Ring": 0x1C,
        "Ability Stud": 0x1D,
        "Guard Earring": 0x1E,
        "Master Earring": 0x1F,
        "Chaos Ring": 0x20,
        "Dark Ring": 0x21,
        "Element Ring": 0x22,
        "Three Stars": 0x23,
        "Power Chain": 0x24,
        "Golem Chain": 0x25,
        "Titan Chain": 0x26,
        "Energy Bangle": 0x27,
        "Angel Bangle": 0x28,
        "Gaia Bangle": 0x29,
        "Magic Armlet": 0x2A,
        "Rune Armlet": 0x2B,
        "Atlas Armlet": 0x2C,
        "Heartguard": 0x2D,
        "Ribbon": 0x2E,
        "Crystal Crown": 0x2F,
        "Brave Warrior": 0x30,
        "Ifrit's Horn": 0x31,
        "Inferno Band": 0x32,
        "White Fang": 0x33,
        "Ray of Light": 0x34,
        "Holy Circlet": 0x35,
        "Raven's Claw": 0x36,
        "Omega Arts": 0x37,
        "EXP Earring": 0x38,
        "Unused 0x39": 0x39,
        "EXP Ring": 0x3A,
        "EXP Bracelet": 0x3B,
        "EXP Necklace": 0x3C,
        "Firagun Band": 0x3D,
        "Blizzagun Band": 0x3E,
        "Thundagun Band": 0x3F,
        "Ifrit Belt": 0x40,
        "Shiva Belt": 0x41,
        "Ramuh Belt": 0x42,
        "Moogle Badge": 0x43,
        "Cosmic Arts": 0x44,
        "Royal Crown": 0x45,
        "Prime Cap": 0x46,
        "Obsidian Ring": 0x47,
        "Unused 0x48": 0x48,
        "Unused 0x49": 0x49,
        "Unused 0x4A": 0x4A,
        "Unused 0x4B": 0x4B,
        "Unused 0x4C": 0x4C,
        "Unused 0x4D": 0x4D,
        "Unused 0x4E": 0x4E,
        "Unused 0x4F": 0x4F,
        "Unused 0x50": 0x50
    }
    obj.weapon_dict = {
        "Empty": 0x00,
        "Kingdom Key": 0x51,
        "Dream Sword": 0x52,
        "Dream Shield": 0x53,
        "Dream Rod": 0x54,
        "Wooden Sword": 0x55,
        "Jungle King": 0x56,
        "Three Wishes": 0x57,
        "Fairy Harp": 0x58,
        "Pumpkinhead": 0x59,
        "Crabclaw": 0x5A,
        "Divine Rose": 0x5B,
        "Spellbinder": 0x5C,
        "Olympia": 0x5D,
        "Lionheart": 0x5E,
        "Metal Chocobo": 0x5F,
        "Oathkeeper": 0x60,
        "Oblivion": 0x61,
        "Lady Luck": 0x62,
        "Wishing Star": 0x63,
        "Ultima Weapon": 0x64,
        "Diamond Dust": 0x65,
        "One-Winged Angel": 0x66,
        "Mage's Staff": 0x67,
        "Morning Star": 0x68,
        "Shooting Star": 0x69,
        "Magus Staff": 0x6A,
        "Wisdom Staff": 0x6B,
        "Warhammer": 0x6C,
        "Silver Mallet": 0x6D,
        "Grand Mallet": 0x6E,
        "Lord Fortune": 0x6F,
        "Violetta": 0x70,
        "Dream Rod (Donald)": 0x71,
        "Save the Queen": 0x72,
        "Wizard’s Relic": 0x73,
        "Meteor Strike": 0x74,
        "Fantasista": 0x75,
        "Unused Weapon (Donald)": 0x76,
        "Knight’s Shield": 0x77,
        "Mythril Shield": 0x78,
        "Onyx Shield": 0x79,
        "Stout Shield": 0x7A,
        "Golem Shield": 0x7B,
        "Adamant Shield": 0x7C,
        "Smasher": 0x7D,
        "Gigas Fist": 0x7E,
        "Genji Shield": 0x7F,
        "Herc’s Shield": 0x80,
        "Dream Shield (Goofy)": 0x81,
        "Save the King": 0x82,
        "Defender": 0x83,
        "Mighty Shield": 0x84,
        "Seven Elements": 0x85,
        "Unused Weapon (Goofy)": 0x86,
        "Spear (Tarzan)": 0x87,
        "No Weapon (Pooh)": 0x88,
        "Sword (Aladdin)": 0x89,
        "No Weapon (Ariel)": 0x8A,
        "No Weapon (Jack)": 0x8B,
        "Dagger (Peter Pan)": 0x8C,
        "Claws (Beast)": 0x8D
    }
    obj.item2_dict = {
        "Tent": 0x8E,
        "Camping Set": 0x8F,
        "Cottage": 0x90,
        "Unused 0x91": 0x91,
        "Unused 0x92": 0x92,
        "Unused 0x93": 0x93,
        "Unused 0x94": 0x94,
        "Ansem's Report 11": 0x95,
        "Ansem's Report 12": 0x96,
        "Ansem's Report 13": 0x97,
        "Power Up": 0x98,
        "Defense Up": 0x99,
        "AP Up": 0x9A,
        "Serenity Power": 0x9B,
        "Dark Matter": 0x9C,
        "Mythril Stone": 0x9D,
        "Fire Arts": 0x9E,
        "Blizzard Arts": 0x9F,
        "Thunder Arts": 0xA0,
        "Cure Arts": 0xA1,
        "Gravity Arts": 0xA2,
        "Stop Arts": 0xA3,
        "Aero Arts": 0xA4,
        "Shiitake Rank": 0xA5,
        "Matsutake Rank": 0xA6,
        "Mystery Mold": 0xA7,
        "Ansem's Report 1": 0xA8,
        "Ansem's Report 2": 0xA9,
        "Ansem's Report 3": 0xAA,
        "Ansem's Report 4": 0xAB,
        "Ansem's Report 5": 0xAC,
        "Ansem's Report 6": 0xAD,
        "Ansem's Report 7": 0xAE,
        "Ansem's Report 8": 0xAF,
        "Ansem's Report 9": 0xB0,
        "Ansem's Report 10": 0xB1,
        "Khama Vol. 8": 0xB2,
        "Salegg Vol. 6": 0xB3,
        "Azal Vol. 3": 0xB4,
        "Mava Vol. 3": 0xB5,
        "Mava Vol. 6": 0xB6,
        "Theon Vol. 6": 0xB7,
        "Nahara Vol. 5": 0xB8,
        "Hafet Vol. 4": 0xB9,
        "Empty Bottle": 0xBA,
        "Old Book": 0xBB,
        "Emblem Piece 1": 0xBC,
        "Emblem Piece 2": 0xBD,
        "Emblem Piece 3": 0xBE,
        "Emblem Piece 4": 0xBF,
        "Log": 0xC0,
        "Cloth": 0xC1,
        "Rope": 0xC2,
        "Seagull Egg": 0xC3,
        "Fish": 0xC4,
        "Mushroom": 0xC5,
        "Coconut": 0xC6,
        "Drinking Water": 0xC7,
        "Navi-G Piece 1": 0xC8,
        "Navi-G Piece 2": 0xC9,
        "Navi-Gummi 1": 0xCA,
        "Navi-G Piece 3": 0xCB,
        "Navi-G Piece 4": 0xCC,
        "Navi-Gummi 2": 0xCD,
        "Watergleam": 0xCE,
        "Naturespark": 0xCF,
        "Fireglow": 0xD0,
        "Earthshine": 0xD1,
        "Crystal Trident": 0xD2,
        "Postcard": 0xD3,
        "Torn Page 1": 0xD4,
        "Torn Page 2": 0xD5,
        "Torn Page 3": 0xD6,
        "Torn Page 4": 0xD7,
        "Torn Page 5": 0xD8,
        "Slide 1": 0xD9,
        "Slide 2": 0xDA,
        "Slide 3": 0xDB,
        "Slide 4": 0xDC,
        "Slide 5": 0xDD,
        "Slide 6": 0xDE,
        "Footprints": 0xDF,
        "Claw Marks": 0xE0,
        "Stench": 0xE1,
        "Antenna": 0xE2,
        "Forget-Me-Not": 0xE3,
        "Jack-In-The-Box": 0xE4,
        "Entry Pass": 0xE5,
        "Hero License": 0xE6,
        "Pretty Stone": 0xE7,
        "Unused 0xE8": 0xE8,
        "Lucid Shard": 0xE9,
        "Lucid Gem": 0xEA,
        "Lucid Crystal": 0xEB,
        "Spirit Shard": 0xEC,
        "Spirit Gem": 0xED,
        "Power Shard": 0xEE,
        "Power Gem": 0xEF,
        "Power Crystal": 0xF0,
        "Blaze Shard": 0xF1,
        "Blaze Gem": 0xF2,
        "Frost Shard": 0xF3,
        "Frost Gem": 0xF4,
        "Thunder Shard": 0xF5,
        "Thunder Gem": 0xF6,
        "Shiny Crystal": 0xF7,
        "Bright Shard": 0xF8,
        "Bright Gem": 0xF9,
        "Bright Crystal": 0xFA,
        "Mystery Goo": 0xFB,
        "Gale": 0xFC,
        "Mythril Shard": 0xFD,
        "Mythril": 0xFE,
        "Orichalcum": 0xFF
    }
    obj.item_dict = obj.item1_dict | obj.accessory_dict | obj.weapon_dict | obj.item2_dict
