def journal_dicts(obj):
    obj.heartlessnames = [
        "Soldier", "Shadow",
        "Powerwild", "Bouncywild",
        "Large Body", "Fat Bandit",
        "Sea Neon", "Sheltering Zone",
        "Bandit", "Pirate",
        "Red Nocturne", "Blue Rhapsody", "Yellow Opera", "Green Requiem",
        "Wizard", "Air Soldier",
        "Pot Spider", "Barrel Spider", "Unused 19",
        "Wight Knight", "Air Pirate", "Gargoyle", "Search Ghost",
        "Aquatank", "Screwdriver",
        "Unused 26", "Battleship",
        "Darkball", "Invisible", "Behemoth",
        "Wyvern", "Angel Star", "Defender",
        "White Mushroom", "Black Fungus", "Rare Truffle"
    ]
    obj.heartless_dict = {
        "Shadow": 0x01,
        "Soldier": 0x00,
        "Large Body": 0x04,
        "Red Nocturne": 0x0A,
        "Blue Rhapsody": 0x0B,
        "Yellow Opera": 0x0C,
        "Green Requiem": 0x0D,
        "Powerwild": 0x02,
        "Bouncywild": 0x03,
        "Air Solider": 0x0F,
        "Bandit": 0x08,
        "Fat Bandit": 0x05,
        "Pot Spider": 0x10,
        "Barrel Spider": 0x11,
        "Search Ghost": 0x16,
        "Sea Neon": 0x06,
        "Sheltering Zone": 0x07,
        "Screwdriver": 0x18,
        "Aquatank": 0x17,
        "Wight Knight": 0x13,
        "Gargoyle": 0x15,
        "Pirate": 0x09,
        "Air Pirate": 0x14,
        "Battleship": 0x1A,
        "Darkball": 0x1B,
        "Defender": 0x20,
        "Wyvern": 0x1E,
        "Wizard": 0x0E,
        "Behemoth": 0x1D,
        "Invisible": 0x1C,
        "Angel Star": 0x1F,
        "White Mushroom": 0x21,
        "Black Fungus": 0x22,
        "Rare Truffle": 0x23,
        "Unused 19": 0x12,
        "Unused 26": 0x19,
    }
    obj.fmheartlessnames = [
        "Soldier", "Shadow",
        "Powerwild", "Bouncywild",
        "Large Body", "Fat Bandit",
        "Sea Neon", "Sheltering Zone",
        "Bandit", "Pirate",
        "Red Nocturne", "Blue Rhapsody", "Yellow Opera", "Green Requiem",
        "Wizard", "Air Soldier",
        "Pot Spider", "Barrel Spider", "Pot Scorpion",
        "Wight Knight", "Air Pirate", "Gargoyle", "Search Ghost",
        "Aquatank", "Screwdriver",
        "Chimera", "Battleship",
        "Darkball", "Invisible", "Behemoth",
        "Wyvern", "Angel Star", "Defender",
        "White Mushroom", "Black Fungus", "Rare Truffle",
        "Unused 37", "Unused 38", "Unused 39",
        "Pink Agaricus", "Neoshadow", "Stealth Soldier", "Gigas Shadow",
        "Sniperwild", "Black Ballade",
        "Jet Balloon", "Unused 47", "Grand Ghost",
        "Destroyed Behemoth", "Arch Behemoth", "Sneak Army"
    ]
    obj.heartless_fm_dict = {
        "Shadow": 0x01,
        "Gigas Shadow": 0x2A,
        "Soldier": 0x00,
        "Stealth Soldier": 0x29,
        "Large Body": 0x04,
        "Red Nocturne": 0x0A,
        "Blue Rhapsody": 0x0B,
        "Yellow Opera": 0x0C,
        "Green Requiem": 0x0D,
        "Black Ballade": 0x2C,
        "Powerwild": 0x02,
        "Bouncywild": 0x03,
        "Sniperwild": 0x2B,
        "Air Solider": 0x0F,
        "Bandit": 0x08,
        "Fat Bandit": 0x05,
        "Pot Spider": 0x10,
        "Barrel Spider": 0x11,
        "Pot Scorpion": 0x12,
        "Search Ghost": 0x16,
        "Grand Ghost": 0x2F,
        "Sea Neon": 0x06,
        "Sheltering Zone": 0x07,
        "Screwdriver": 0x18,
        "Aquatank": 0x17,
        "Wight Knight": 0x13,
        "Gargoyle": 0x15,
        "Chimera": 0x19,
        "Pirate": 0x09,
        "Air Pirate": 0x14,
        "Battleship": 0x1A,
        "Jet Balloon": 0x2D,
        "Darkball": 0x1B,
        "Defender": 0x20,
        "Wyvern": 0x1E,
        "Wizard": 0x0E,
        "Behemoth": 0x1D,
        "Destroyed Behemoth": 0x30,
        "Arch Behemoth": 0x31,
        "Invisible": 0x1C,
        "Angel Star": 0x1F,
        "Neoshadow": 0x28,
        "White Mushroom": 0x21,
        "Black Fungus": 0x22,
        "Rare Truffle": 0x23,
        "Pink Agaricus": 0x27,
        "Sneak Army": 0x32,
        "Unused 37": 0x24,
        "Unused 38": 0x25,
        "Unused 39": 0x26,
        "Unused 47": 0x2E,
    }
    # The value is the number of parts.
    obj.chronicles_dict = {
        "Sora's Story": 5,
        "Wonderland": 3,
        "Olympus Coliseum": 3,
        "Deep Jungle": 3,
        "Agrabah": 3,
        "Monstro": 3,
        "Hundred Acre Woods": 2,
        "Atlantica": 3,
        "Halloween Town": 3,
        "Neverland": 3,
    }
    # Byte index * 16 + bit index
    # Characters with multiple entry flags only have 1 set at a time.
    obj.journal_chars_1_dict = {
        # Page 1
        "Sora": {
            "Part 1": 0x07,
            "Part 2": 0x06,
        },
        "Riku": {
            "Part 1": 0x05,
            "Part 2": 0x04,
            "Part 3": 0x03,
            "Part 4": 0x02,
        },
        "Kairi": {
            "Part 1": 0x01,
            "Part 2": 0x00,
        },
        "Mickey Mouse": 0x17,
        "Donald Duck": {
            "Part 1": 0x16,
            "Part 2": 0x15,
        },
        "Goofy": {
            "Part 1": 0x14,
            "Part 2": 0x13,
        },
        "Minnie Mouse": 0x12,
        "Daisy Duck": 0x11,
        # Page 2
        "Pluto": 0x10,
        "Chip": 0x27,
        "Dale": 0x26,
        "Huey": 0x25,
        "Dewey": 0x24,
        "Louie": 0x23,
        "Merlin": 0x22,
        "Fairy Godmother": 0x21,
        # Page 3
        "Pongo": 0x20,
        "Perdita": 0x37,
        "99 Puppies": 0x36,
        "Brooms": 0x35,
        "Leon": 0x34,
        "Yuffie": 0x33,
        "Aerith": 0x32,
        "Cloud": 0x31,
        # Page 4
        "Sephiroth": 0x142,
        "Cid": 0x30,
        "Tidus": 0x47,
        "Selphie": 0x46,
        "Wakka": 0x45,
        "Moogles": 0x44,
        "Snow White": 0x42,
        "Cinderella": 0x41,
        # Page 5
        "Aurora": 0x40,
        "Bell": 0x57,
        "Beast": 0x56,
        "Maleficent":{
            "Part 1": 0x55,
            "Part 2": 0x54,
            "Part 3": 0x53,
        },
        "Dragon": 0x52,
        "Ansem": {
            "Part 1": 0x43,
            "Part 2": 0x51,
        },
        "?": 0x156,
    }
    obj.journal_chars_2_dict = {
        # Page 1
        "Dumbo": 0x50,
        "Bambi": 0x67,
        "Mushu": 0x66,
        "Simba": 0x65,
        "Alice": {
            "Part 1": 0x64,
            "Part 2": 0x63,
        },
        "Queen of Hearts": 0x62,
        "Cards (Hearts)": 0x61,
        "Cards (Spades)": 0x60,
        # Page 2
        "White Rabbit": 0x77,
        "Chesire Cat": 0x76,
        "Doorknob": 0x75,
        "Hercules": 0x74,
        "Philoctetes": 0x73,
        "Hades": {
            "Part 1": 0x72,
            "Part 2": 0x71,
        },
        "Cerberus": 0x70,
        "Rock Titan": 0x87,
        # Page 3
        "Ice Titan": 0x141,
        "Tarzan": 0x86,
        "Jane Porter": 0x85,
        "Clayton": {
            "Part 1": 0x84,
            "Part 2": 0x83,
        },
        "Terk": 0x82,
        "Kerchak": 0x81,
        "Kala": 0x80,
        "Sabor": 0x97,
        # Page 4
        "Aladdin": {
            "Part 1": 0x96,
            "Part 2": 0x95,
        },
        "Genie": {
            "Part 1": 0x94,
            "Part 2": 0x93,
        },
        "Jasmine": {
            "Part 1": 0x92,
            "Part 2": 0x140,
        },
        "Jafar": {
            "Part 1": 0x91,
            "Part 2": 0x90,
        },
        "Jafar-Genie": 0xA7,
        "Abu": 0xA6,
        "Iago": 0xA5,
        "Carpet": 0xA4,
        # Page 5
        "Pinocchio": {
            "Part 1": 0xA3,
            "Part 2": 0xA2,
        },
        "Geppetto": {
            "Part 1": 0xA1,
            "Part 2": 0xA0,
        },
        "Jiminy Cricket": 0xB7,
        "Ariel": {
            "Part 1": 0xB6,
            "Part 2": 0xB5,
        },
        "King Triton": 0xB4,
        "Ursula": {
            "Part 1": 0xB3,
            "Part 2": 0xB2,
        },
        "Sebastian": 0xB1,
        "Flounder": 0xB0,
        # Page 6
        "Jetsam": 0xC7,
        "Flotsam": 0xC6,
        "Jack Skellington": 0xC5,
        "Sally": 0xC4,
        "Oogie Boogie": {
            "Part 1": 0xC3,
            "Part 2": 0xC2,
        },
        "Dr. Finkelstein": 0xC1,
        "Zero": 0xC0,
        "Lock": 0xD7,
        # Page 7
        "Shock": 0xD6,
        "Barrel": 0xD5,
        "The Mayor": 0xD4,
        "Peter Pan": 0xD3,
        "Tinker Bell": {
            "Part 1": 0xD2,
            "Part 2": 0xD1,
        },
        "Wendy": 0xD0,
        "Captain Hook": {
            "Part 1": 0xE7,
            "Part 2": 0xE6,
        },
        "Mr. Smee": 0xE5,
        # Page 8
        "The Crocodile": 0xE4,
        "Winnie the Pooh": 0xE3,
        "Piglet": 0xE2,
        "Tigger": 0xE1,
        "Owl": 0xE0,
        "Rabbit": 0xF7,
        "Eeyore": 0xF6,
        "Roo": 0xF5,
    }
    obj.journal_boss_dict = {
        "Darkside": 0x132,
        "Guard Armor": 0x131,
        "Red Armor": 0x161,
        "Opposite Armor": 0x130,
        "Trickmaster": 0x147,
        "Stealth Sneak": 0x146,
        "Pot Centipede": 0x145,
        "Parasite Cage": 0x144,
        "Kurt Zisa": 0x157,
        "Phantom": 0x143,
    }

def trinity_dicts(obj):
    obj.trinity_names = [
        "Trinity Jump",
        "Trinity Charge",
        "Trinity Ladder",
        "Trinity Push",
        "Trinity Detect",
    ]
    obj.trinity_dict_list = [
        {
            "Traverse Town: 1st District: At the World Exit": 0x06,
            "Traverse Town: 1st District: Below the balcony": 0x05,
            "Traverse Town: Magician's Study": 0x450,
            "Traverse Town: 3rd District": 0x473,
            "Wonderland: Lotus Forest: 1": 0x25,
            "Wonderland: Lotus Forest: 2": 0x26,
            "Olympus Coliseum: Coliseum Gates: 1": 0x45,
            "Olympus Coliseum: Coliseum Gates: 2": 0x46,
            "Deep Jungle: Climbing Trees": 0x64,
            "Deep Jungle: Camp": 0x65,
            "Agrabah: Bazaar": 0x86,
            "Agrabah: Silent Chamber": 0x82,
            "Monstro: Chamber 5": 0xA3,
            "Monstro: Throat": 0xA4,
            "Monstro: Mouth": 0xA5,
            "Hollow Bastion: Dungeon": 0xF5,
            "Hollow Bastion: Great Crest": 0xF6,
        },
        {
            "Traverse Town: 1st District": 0x447,
            "Traverse Town: 2nd District": 0x454,
            "Traverse Town: Alleyway": 0x455,
            "Agrabah: Treasure Room": 0x83,
            "Halloween Town: Oogie's Manor": 0xC6,
            "Hollow Bastion: Entrance Hall": 0x107,
        },
        {
            "Traverse Town: Accessory Shop": 0x463,
            "Wonderland: Bizarre Room": 0x23,
            "Wonderland: Rabbit Hole": 0x24,
            "Olympus Coliseum: Coliseum Gates": 0x43,
            "Deep Jungle: Treetop": 0x63,
            "Agrabah: Agrabah: Storage": 0x85,
            "Monstro: Mouth": 0xA6,
            "Neverland: Ship: Cabin": 0xE0,
            "Hollow Bastion: Library": 0x106,
        },
        {
            "Traverse Town: Mystical House": 0x16,
            # Has special treatment since it's out of bounds.
            "Olympus Coliseum: Coliseum: Lobby": 0x1A40,
            "Agrabah: Cave: Hall": 0x84,
            "Neverland: Ship: Hold": 0xE1,
        },
        {
            "Traverse Town: Secret Waterway": 0x07,
            "Wonderland: Lotus Forest": 0x27,
            "Olympus Coliseum: Coliseum Gates": 0x42,
            "Deep Jungle: Cavern of Hearts": 0x67,
            "Agrabah: Cave: Entrance": 0x87,
            "Monstro: Chamber 6": 0xA7,
            "Atlantica: Triton's Palace": 0x137,
            "Halloween Town: Moonlight Hill": 0xC7,
            "Neverland: Pirate Ship": 0xE7,
            "Hollow Bastion: Rising Falls": 0xF7,
        },
    ]

def minigame_dicts(obj):
    # All of tbem are times
    # Values are the indices where the ints start in KH1.oc_minigames
    """
        "Training": {
            "Easy": 0x14,
            "Advanced": 0x18,
        },
    """
    obj.oc_minigame_dict = {
        "Phil Cup": {
            "1st Place": 0x00,
            "2nd Place": 0x20,
            "3rd Place": 0x24,
            "4th Place": 0x28,
            "5th Place": 0x2C,
        },
        "Pegasus Cup": {
            "1st Place": 0x04,
            "2nd Place": 0x30,
            "3rd Place": 0x34,
            "4th Place": 0x38,
            "5th Place": 0x3C,
        },
        "Hercules Cup": {
            "1st Place": 0x08,
            "2nd Place": 0x40,
            "3rd Place": 0x44,
            "4th Place": 0x48,
            "5th Place": 0x4C,
        },
        "Hades Cup": {
            "1st Place": 0x0C,
            "2nd Place": 0x50,
            "3rd Place": 0x54,
            "4th Place": 0x58,
            "5th Place": 0x5C,
        },
    }
    # Keys are the tab/journal entry names
    # Here indices refer to KH1.minigames
    obj.minigame_dict = {
        "Jungle Slider": {
            "Green Serpent": {
                "1st Place": 0x00,
                "2nd Place": 0x04,
                "3rd Place": 0x08,
                "4th Place": 0x0C,
                "5th Place": 0x10,
            },
            "Splash Tunnel": {
                "1st Place": 0x14,
                "2nd Place": 0x18,
                "3rd Place": 0x1C,
                "4th Place": 0x20,
                "5th Place": 0x24,
            },
            "Jade Spiral": {
                "1st Place": 0x28,
                "2nd Place": 0x2C,
                "3rd Place": 0x30,
                "4th Place": 0x34,
                "5th Place": 0x38,
            },
            "Panic Fall": {
                "1st Place": 0x3C,
                "2nd Place": 0x40,
                "3rd Place": 0x44,
                "4th Place": 0x48,
                "5th Place": 0x4C,
            },
            "Shadow Cavern": {
                "1st Place": 0x50,
                "2nd Place": 0x54,
                "3rd Place": 0x58,
                "4th Place": 0x5C,
                "5th Place": 0x60,
            },
        },
        "Vine Jump": {
            "Jump Course": {
                "1st Place": 0x64,
                "2nd Place": 0x68,
                "3rd Place": 0x6C,
                "4th Place": 0x70,
                "5th Place": 0x74,
            },
            "Trap Course": {
                "1st Place": 0x78,
                "2nd Place": 0x7C,
                "3rd Place": 0x80,
                "4th Place": 0x84,
                "5th Place": 0x88,
            },
            "Acrobatic Course": {
                "1st Place": 0x8C,
                "2nd Place": 0x90,
                "3rd Place": 0x94,
                "4th Place": 0x98,
                "5th Place": 0x9C,
            },
            "Expert Course": {
                "1st Place": 0xA0,
                "2nd Place": 0xA4,
                "3rd Place": 0xA8,
                "4th Place": 0xAC,
                "5th Place": 0xB0,
            },
        },
        "Pooh's Hunny Hunt": {
            "1st Place": 0xB4,
            "2nd Place": 0xB8,
            "3rd Place": 0xBC,
            "4th Place": 0xC0,
            "5th Place": 0xC4,
        },
        "Block Tigger": {
            "1st Place": 0xC8,
            "2nd Place": 0xCC,
            "3rd Place": 0xD0,
            "4th Place": 0xD4,
            "5th Place": 0xD8,
        },
        "Pooh's Swing": {
            "1st Place": 0xDC,
            "2nd Place": 0xE0,
            "3rd Place": 0xE4,
            "4th Place": 0xE8,
            "5th Place": 0xEC,
        },
        "Tigger's Giant Pot": {
            "1st Place": 0xF0,
            "2nd Place": 0xF4,
            "3rd Place": 0xF8,
            "4th Place": 0xFC,
            "5th Place": 0x100,
        },
        "Pooh's Muddy Path": {
            "1st Place": 0x104,
            "2nd Place": 0x108,
            "3rd Place": 0x10C,
            "4th Place": 0x110,
            "5th Place": 0x114,
        },
    }
    obj.minigames_with_sub = {
        "Jungle Slider",
        "Vine Jump",
        # Not needed since special case
        "Olympus Coliseum",
    }
    obj.minigames_with_scores = {
        "Pooh's Hunny Hunt": "licks",
        "Block Tigger": "points",
        "Pooh's Swing": "yd.",
    }
