def game_records_dicts(obj):
    @property
    def arena_missions_dict(self):
        if hasattr(self, "fm") and self.fm:
            return {
                "Collect 300 medals during the game.": 0x00,
                "Collect 1,000 medals during the game.": 0x01,
                "Collect 3,333 medals during the game.": 0x02,
                "Collect 5,555 medals during the game.": 0x03,
                "Collect 7,777 medals during the game.": 0x04,
                "Collect 9,999 medals during the game.": 0x05,
                "Complete \"Day of Reckoning\".": 0x06,
                "Complete \"Wheels of Misfortune\".": 0x07,
                "Complete \"Risky Riches\".": 0x10,
                "Complete \"Weaver Fever\".": 0x11,
                "Complete \"Sinister Sentinel\".": 0x12,
                "Complete \"Dead Ringer\".": 0x13,
                "Complete \"Combined Threat\".": 0x14,
                "Complete \"Treasure Tussle\".": 0x15,
                "Complete \"Harsh Punishment\".": 0x16,
                "Complete \"A Time to Chill\".": 0x17,
                "Complete \"Copycat Crisis\".": 0x20,
                "Complete \"Keepers of the Arena\".": 0x21,
                "Complete \"Monster of the Sea\".": 0x26,
                "Complete \"Villains' Vendetta\".": 0x27,
                "Complete \"Light's Lessons\".": 0x30,
                "Country Chase:\n\tFinish five laps in 2 minutes 30 seconds.": 0x22,
                "Disney Drive:\n\tFinish five laps in 5 minutes.": 0x23,
                "Grand Spree:\n\tFinish five laps in 5 minutes.": 0x24,
                "Castle Circuit:\n\tFinish five laps in 5 minutes 30 seconds.": 0x25,
                "Play the Command Board more than once.": 0x31,
                "Play the Command Board more than 3 times.": 0x32,
                "Play the Command Board more than 5 times.": 0x33,
                "Play the Command Board more than 7 times.": 0x34,
            }
        elif hasattr(self, "version") and self.version == 0:
            return {
                "Collect 300 medals during the game.": 0x00,
                "Collect 1,000 medals during the game.": 0x01,
                "Collect 3,000 medals during the game.": 0x02,
                "Collect 5,000 medals during the game.": 0x03,
                "Collect 9,999 medals during the game.": 0x04,
                "Complete \"Day of Reckoning\".": 0x06,
                "Complete \"Wheels of Misfortune\".": 0x07,
                "Complete \"Risky Riches\".": 0x10,
                "Complete \"Weaver Fever\".": 0x11,
                "Complete \"Sinister Sentinel\".": 0x12,
                "Complete \"Dead Ringer\".": 0x13,
                "Complete \"Combined Threat\".": 0x14,
                "Complete \"Treasure Tussle\".": 0x15,
                "Complete \"Harsh Punishment\".": 0x16,
                "Complete \"A Time to Chill\".": 0x17,
                "Complete \"Copycat Crisis\".": 0x20,
                "Complete \"Keepers of the Arena\".": 0x21,
                "Country Chase:\n\tFinish three laps in 1 minutes 30 seconds.": 0x22,
                "\tFinish five laps in 2 minutes 30 seconds.": 0x23,
                "Disney Drive:\n\tFinish three laps in 3 minutes.": 0x24,
                "\tFinish five laps in 5 minutes.": 0x25,
                "Grand Spree:\n\tFinish five laps in 5 minutes.": 0x26,
                "\tFinish nine laps in 9 minutes.": 0x27,
                "Win a game on the Keyblade Board.": 0x31,
                "Win a game on the Royal Board.": 0x32,
                "Win a game on the Spaceship Board.": 0x33,
                "Win a game on the Toon Board.": 0x34,
                "Win a game on the Hunny Pot Board.": 0x35,
                "Win a game on the Secret Board.": 0x30,
            }
        else:
            return {
                "Collect 300 medals during the game.": 0x00,
                "Collect 1,000 medals during the game.": 0x01,
                "Collect 3,333 medals during the game.": 0x02,
                "Collect 5,555 medals during the game.": 0x03,
                "Collect 7,777 medals during the game.": 0x04,
                "Collect 9,999 medals during the game.": 0x05,
                "Complete \"Day of Reckoning\".": 0x06,
                "Complete \"Wheels of Misfortune\".": 0x07,
                "Complete \"Risky Riches\".": 0x10,
                "Complete \"Weaver Fever\".": 0x11,
                "Complete \"Sinister Sentinel\".": 0x12,
                "Complete \"Dead Ringer\".": 0x13,
                "Complete \"Combined Threat\".": 0x14,
                "Complete \"Treasure Tussle\".": 0x15,
                "Complete \"Harsh Punishment\".": 0x16,
                "Complete \"A Time to Chill\".": 0x17,
                "Complete \"Copycat Crisis\".": 0x20,
                "Complete \"Keepers of the Arena\".": 0x21,
                "Country Chase:\n\tFinish five laps in 2 minutes 30 seconds.": 0x22,
                "Disney Drive:\n\tFinish five laps in 5 minutes.": 0x23,
                "Grand Spree:\n\tFinish five laps in 5 minutes.": 0x24,
                "Castle Circuit:\n\tFinish five laps in 5 minutes 30 seconds.": 0x25,
                "Win a game on the Keyblade Board.": 0x31,
                "Win a game on the Royal Board.": 0x32,
                "Win a game on the Spaceship Board.": 0x33,
                "Win a game on the Toon Board.": 0x34,
                "Win a game on the Hunny Pot Board.": 0x35,
                "Win a game on the Skull Board.": 0x27,
                "Win a game on the Secret Board.": 0x30,
            }
    type(obj).arena_missions_dict = arena_missions_dict
