def dicts(obj):
    obj.character_dict = {
        "Sora": 0,
        "Donald": 1,
        "Goofy": 2,
        "Tarzan": 3,
        "Winnie the Pooh": 4,
        "Aladdin": 5,
        "Ariel": 6,
        "Jack Skellington": 7,
        "Peter Pan": 8,
        "Beast": 9,
        "None": 255
    }
    obj.ability_dict = {
        "Empty": 0x00,
        "High Jump": 0x01,
        "Mermaid Kick": 0x02,
        "Glide": 0x03,
        "Superglide": 0x04,
        "Treasure Magnet": 0x05,
        "Combo Plus": 0x06,
        "Air Combo Plus": 0x07,
        "Critical Plus": 0x08,
        "Second Wind": 0x09,
        "Scan": 0x0A,
        "Sonic Blade": 0x0B,
        "Ars Arcanum": 0x0C,
        "Strike Raid": 0x0D,
        "Ragnarok": 0x0E,
        "Trinity Limit": 0x0F,
        "Cheer": 0x10,
        "Vortex": 0x11,
        "Aerial Sweep": 0x12,
        "Counterattack": 0x13,
        "Blitz": 0x14,
        "Guard": 0x15,
        "Dodge Roll": 0x16,
        "MP Haste": 0x17,
        "MP Rage": 0x18,
        "Second Chance": 0x19,
        "Berserk": 0x1A,
        "Jackpot": 0x1B,
        "Lucky Strike": 0x1C,
        "Charge": 0x1D,
        "Rocket": 0x1E,
        "Tornado": 0x1F,
        "MP Gift": 0x20,
        "Raging Boar": 0x21,
        "Asp’s Bite": 0x22,
        "Healing Herb": 0x23,
        "Wind Armor": 0x24,
        "Crescent": 0x25,
        "Sandstorm": 0x26,
        "Applause!": 0x27,
        "Blazing Fury": 0x28,
        "Icy Terror": 0x29,
        "Bolts of Sorrow": 0x2A,
        "Ghostly Scream": 0x2B,
        "Hummingbird": 0x2C,
        "Time-Out": 0x2D,
        "Storm’s Eye": 0x2E,
        "Ferocious Lunge": 0x2F,
        "Furious Bellow": 0x30,
        "Spiral Wave": 0x31,
        "Thunder Potion": 0x32,
        "Cure Potion": 0x33,
        "Aero Potion": 0x34,
        # FM exclusives
        "Slapshot": 0x35,
        "Sliding Dash": 0x36,
        "Hurricane Blast": 0x37,
        "Ripple Drive": 0x38,
        "Stun Impact": 0x39,
        "Gravity Break": 0x3A,
        "Zantetsuken": 0x3B,
        "Tech Boost": 0x3C,
        "Encounter Plus": 0x3D,
        "Leaf Bracer": 0x3E,
        "Evolution": 0x3F,
        # Remix exclusives
        "EXP Zero": 0x40,
        "Combo Master": 0x41
    }
    obj.item1_dict = {
        "Empty": 0x00,
        "Potion": 0x01,
        "Hi-Potion": 0x02,
        "Ether": 0x03,
        "Elixir": 0x04,
        "Unused 0x05": 0x05,
        "Mega-Potion": 0x06,
        "Mega-Ether": 0x07,
        "Megalixir": 0x08,
        "Fury Stone": 0x09,
        "Power Stone": 0x0A,
        "Energy Stone": 0x0B,
        "Blazing Stone": 0x0C,
        "Frost Stone": 0x0D,
        "Lightning Stone": 0x0E,
        "Dazzling Stone": 0x0F,
        "Stormy Stone": 0x10
    }
    obj.accessory_dict =  {
        "Empty": 0x00,
        "Protect Chain": 0x11,
        "Protera Chain": 0x12,
        "Protega Chain": 0x13,
        "Fire Ring": 0x14,
        "Fira Ring": 0x15,
        "Firaga Ring": 0x16,
        "Blizzard Ring": 0x17,
        "Blizzara Ring": 0x18,
        "Blizzaga Ring": 0x19,
        "Thunder Ring": 0x1A,
        "Thundara Ring": 0x1B,
        "Thundaga Ring": 0x1C,
        "Ability Stud": 0x1D,
        "Guard Earring": 0x1E,
        "Master Earring": 0x1F,
        "Chaos Ring": 0x20,
        "Dark Ring": 0x21,
        "Element Ring": 0x22,
        "Three Stars": 0x23,
        "Power Chain": 0x24,
        "Golem Chain": 0x25,
        "Titan Chain": 0x26,
        "Energy Bangle": 0x27,
        "Angel Bangle": 0x28,
        "Gaia Bangle": 0x29,
        "Magic Armlet": 0x2A,
        "Rune Armlet": 0x2B,
        "Atlas Armlet": 0x2C,
        "Heartguard": 0x2D,
        "Ribbon": 0x2E,
        "Crystal Crown": 0x2F,
        "Brave Warrior": 0x30,
        "Ifrit's Horn": 0x31,
        "Inferno Band": 0x32,
        "White Fang": 0x33,
        "Ray of Light": 0x34,
        "Holy Circlet": 0x35,
        "Raven's Claw": 0x36,
        "Omega Arts": 0x37,
        "EXP Earring": 0x38,
        "Unused 0x39": 0x39,
        "EXP Ring": 0x3A,
        "EXP Bracelet": 0x3B,
        "EXP Necklace": 0x3C,
        "Firagun Band": 0x3D,
        "Blizzagun Band": 0x3E,
        "Thundagun Band": 0x3F,
        "Ifrit Belt": 0x40,
        "Shiva Belt": 0x41,
        "Ramuh Belt": 0x42,
        "Moogle Badge": 0x43,
        "Cosmic Arts": 0x44,
        "Royal Crown": 0x45,
        "Prime Cap": 0x46,
        "Obsidian Ring": 0x47,
        "Unused 0x48": 0x48,
        "Unused 0x49": 0x49,
        "Unused 0x4A": 0x4A,
        "Unused 0x4B": 0x4B,
        "Unused 0x4C": 0x4C,
        "Unused 0x4D": 0x4D,
        "Unused 0x4E": 0x4E,
        "Unused 0x4F": 0x4F,
        "Unused 0x50": 0x50
    }
    obj.weapon_dict = {
        "Empty": 0x00,
        "Kingdom Key": 0x51,
        "Dream Sword": 0x52,
        "Dream Shield": 0x53,
        "Dream Rod": 0x54,
        "Wooden Sword": 0x55,
        "Jungle King": 0x56,
        "Three Wishes": 0x57,
        "Fairy Harp": 0x58,
        "Pumpkinhead": 0x59,
        "Crabclaw": 0x5A,
        "Divine Rose": 0x5B,
        "Spellbinder": 0x5C,
        "Olympia": 0x5D,
        "Lionheart": 0x5E,
        "Metal Chocobo": 0x5F,
        "Oathkeeper": 0x60,
        "Oblivion": 0x61,
        "Lady Luck": 0x62,
        "Wishing Star": 0x63,
        "Ultima Weapon": 0x64,
        "Diamond Dust": 0x65,
        "One-Winged Angel": 0x66,
        "Mage's Staff": 0x67,
        "Morning Star": 0x68,
        "Shooting Star": 0x69,
        "Magus Staff": 0x6A,
        "Wisdom Staff": 0x6B,
        "Warhammer": 0x6C,
        "Silver Mallet": 0x6D,
        "Grand Mallet": 0x6E,
        "Lord Fortune": 0x6F,
        "Violetta": 0x70,
        "Dream Rod (Donald)": 0x71,
        "Save the Queen": 0x72,
        "Wizard’s Relic": 0x73,
        "Meteor Strike": 0x74,
        "Fantasista": 0x75,
        "Unused Weapon (Donald)": 0x76,
        "Knight’s Shield": 0x77,
        "Mythril Shield": 0x78,
        "Onyx Shield": 0x79,
        "Stout Shield": 0x7A,
        "Golem Shield": 0x7B,
        "Adamant Shield": 0x7C,
        "Smasher": 0x7D,
        "Gigas Fist": 0x7E,
        "Genji Shield": 0x7F,
        "Herc’s Shield": 0x80,
        "Dream Shield (Goofy)": 0x81,
        "Save the King": 0x82,
        "Defender": 0x83,
        "Mighty Shield": 0x84,
        "Seven Elements": 0x85,
        "Unused Weapon (Goofy)": 0x86,
        "Spear (Tarzan)": 0x87,
        "No Weapon (Pooh)": 0x88,
        "Sword (Aladdin)": 0x89,
        "No Weapon (Ariel)": 0x8A,
        "No Weapon (Jack)": 0x8B,
        "Dagger (Peter Pan)": 0x8C,
        "Claws (Beast)": 0x8D
    }
    obj.item2_dict = {
        "Tent": 0x8E,
        "Camping Set": 0x8F,
        "Cottage": 0x90,
        "Unused 0x91": 0x91,
        "Unused 0x92": 0x92,
        "Unused 0x93": 0x93,
        "Unused 0x94": 0x94,
        "Ansem's Report 11": 0x95,
        "Ansem's Report 12": 0x96,
        "Ansem's Report 13": 0x97,
        "Power Up": 0x98,
        "Defense Up": 0x99,
        "AP Up": 0x9A,
        "Serenity Power": 0x9B,
        "Dark Matter": 0x9C,
        "Mythril Stone": 0x9D,
        "Fire Arts": 0x9E,
        "Blizzard Arts": 0x9F,
        "Thunder Arts": 0xA0,
        "Cure Arts": 0xA1,
        "Gravity Arts": 0xA2,
        "Stop Arts": 0xA3,
        "Aero Arts": 0xA4,
        "Shiitake Rank": 0xA5,
        "Matsutake Rank": 0xA6,
        "Mystery Mold": 0xA7,
        "Ansem's Report 1": 0xA8,
        "Ansem's Report 2": 0xA9,
        "Ansem's Report 3": 0xAA,
        "Ansem's Report 4": 0xAB,
        "Ansem's Report 5": 0xAC,
        "Ansem's Report 6": 0xAD,
        "Ansem's Report 7": 0xAE,
        "Ansem's Report 8": 0xAF,
        "Ansem's Report 9": 0xB0,
        "Ansem's Report 10": 0xB1,
        "Khama Vol. 8": 0xB2,
        "Salegg Vol. 6": 0xB3,
        "Azal Vol. 3": 0xB4,
        "Mava Vol. 3": 0xB5,
        "Mava Vol. 6": 0xB6,
        "Theon Vol. 6": 0xB7,
        "Nahara Vol. 5": 0xB8,
        "Hafet Vol. 4": 0xB9,
        "Empty Bottle": 0xBA,
        "Old Book": 0xBB,
        "Emblem Piece 1": 0xBC,
        "Emblem Piece 2": 0xBD,
        "Emblem Piece 3": 0xBE,
        "Emblem Piece 4": 0xBF,
        "Log": 0xC0,
        "Cloth": 0xC1,
        "Rope": 0xC2,
        "Seagull Egg": 0xC3,
        "Fish": 0xC4,
        "Mushroom": 0xC5,
        "Coconut": 0xC6,
        "Drinking Water": 0xC7,
        "Navi-G Piece 1": 0xC8,
        "Navi-G Piece 2": 0xC9,
        "Navi-Gummi 1": 0xCA,
        "Navi-G Piece 3": 0xCB,
        "Navi-G Piece 4": 0xCC,
        "Navi-Gummi 2": 0xCD,
        "Watergleam": 0xCE,
        "Naturespark": 0xCF,
        "Fireglow": 0xD0,
        "Earthshine": 0xD1,
        "Crystal Trident": 0xD2,
        "Postcard": 0xD3,
        "Torn Page 1": 0xD4,
        "Torn Page 2": 0xD5,
        "Torn Page 3": 0xD6,
        "Torn Page 4": 0xD7,
        "Torn Page 5": 0xD8,
        "Slide 1": 0xD9,
        "Slide 2": 0xDA,
        "Slide 3": 0xDB,
        "Slide 4": 0xDC,
        "Slide 5": 0xDD,
        "Slide 6": 0xDE,
        "Footprints": 0xDF,
        "Claw Marks": 0xE0,
        "Stench": 0xE1,
        "Antenna": 0xE2,
        "Forget-Me-Not": 0xE3,
        "Jack-In-The-Box": 0xE4,
        "Entry Pass": 0xE5,
        "Hero License": 0xE6,
        "Pretty Stone": 0xE7,
        "Unused 0xE8": 0xE8,
        "Lucid Shard": 0xE9,
        "Lucid Gem": 0xEA,
        "Lucid Crystal": 0xEB,
        "Spirit Shard": 0xEC,
        "Spirit Gem": 0xED,
        "Power Shard": 0xEE,
        "Power Gem": 0xEF,
        "Power Crystal": 0xF0,
        "Blaze Shard": 0xF1,
        "Blaze Gem": 0xF2,
        "Frost Shard": 0xF3,
        "Frost Gem": 0xF4,
        "Thunder Shard": 0xF5,
        "Thunder Gem": 0xF6,
        "Shiny Crystal": 0xF7,
        "Bright Shard": 0xF8,
        "Bright Gem": 0xF9,
        "Bright Crystal": 0xFA,
        "Mystery Goo": 0xFB,
        "Gale": 0xFC,
        "Mythril Shard": 0xFD,
        "Mythril": 0xFE,
        "Orichalcum": 0xFF
    }
    obj.item_dict = obj.item1_dict | obj.accessory_dict | obj.weapon_dict | obj.item2_dict
    obj.world_dict = {
        0x00: "Dive to the Heart",
        0x01: "Destiny Islands",
        0x02: "Disney Castle",
        0x03: "Traverse Town",
        0x04: "Wonderland",
        0x05: "Deep Jungle",
        0x06: "Hundred Acre Woods",
        #0x07: "Unused 0x07",
        0x08: "Agrabah",
        0x09: "Atlantica",
        0x0A: "Halloween Town",
        0x0B: "Olympus Coliseum",
        0x0C: "Monstro",
        0x0D: "Neverland",
        #0x0E: "Unused 0x0E",
        0x0F: "Hollow Bastion",
        0x10: "End of the World"
    }
    obj.magicnames = ["Fire", "Blizzard", "Thunder", "Cure", "Gravity", "Stop", "Aero"]
    obj.magicnames2 = ["Fira", "Blizzara", "Thundara", "Cura", "Gravira", "Stopra", "Aerora"]
    obj.magicnames3 = ["Firaga", "Blizzaga", "Thundaga", "Curaga", "Graviga", "Stopga", "Aeroga"]
    obj.heartlessnames = [
        "Soldier", "Shadow",
        "Powerwild", "Bouncywild",
        "Large Body", "Fat Bandit",
        "Sea Neon", "Sheltering Zone",
        "Bandit", "Pirate",
        "Red Nocturne", "Blue Rhapsody", "Yellow Opera", "Green Requiem",
        "Wizard", "Air Soldier",
        "Pot Spider", "Barrel Spider", "Unused 19",
        "Wight Knight", "Air Pirate", "Gargoyle", "Search Ghost",
        "Aquatank", "Screwdriver",
        "Unused 26", "Battleship",
        "Darkball", "Invisible", "Behemoth",
        "Wyvern", "Angel Star", "Defender",
        "White Mushroom", "Black Fungus", "Rare Truffle"
    ]
    obj.heartless_dict = {
        "Shadow": 0x01,
        "Soldier": 0x00,
        "Large Body": 0x04,
        "Red Nocturne": 0x0A,
        "Blue Rhapsody": 0x0B,
        "Yellow Opera": 0x0C,
        "Green Requiem": 0x0D,
        "Powerwild": 0x02,
        "Bouncywild": 0x03,
        "Air Solider": 0x0F,
        "Bandit": 0x08,
        "Fat Bandit": 0x05,
        "Pot Spider": 0x10,
        "Barrel Spider": 0x11,
        "Search Ghost": 0x16,
        "Sea Neon": 0x06,
        "Sheltering Zone": 0x07,
        "Screwdriver": 0x18,
        "Aquatank": 0x17,
        "Wight Knight": 0x13,
        "Gargoyle": 0x15,
        "Pirate": 0x09,
        "Air Pirate": 0x14,
        "Battleship": 0x1A,
        "Darkball": 0x1B,
        "Defender": 0x20,
        "Wyvern": 0x1E,
        "Wizard": 0x0E,
        "Behemoth": 0x1D,
        "Invisible": 0x1C,
        "Angel Star": 0x1F,
        "White Mushroom": 0x21,
        "Black Fungus": 0x22,
        "Rare Truffle": 0x23,
        "Unused 19": 0x12,
        "Unused 26": 0x19,
    }
    obj.fmheartlessnames = [
        "Soldier", "Shadow",
        "Powerwild", "Bouncywild",
        "Large Body", "Fat Bandit",
        "Sea Neon", "Sheltering Zone",
        "Bandit", "Pirate",
        "Red Nocturne", "Blue Rhapsody", "Yellow Opera", "Green Requiem",
        "Wizard", "Air Soldier",
        "Pot Spider", "Barrel Spider", "Pot Scorpion",
        "Wight Knight", "Air Pirate", "Gargoyle", "Search Ghost",
        "Aquatank", "Screwdriver",
        "Chimera", "Battleship",
        "Darkball", "Invisible", "Behemoth",
        "Wyvern", "Angel Star", "Defender",
        "White Mushroom", "Black Fungus", "Rare Truffle",
        "Unused 37", "Unused 38", "Unused 39",
        "Pink Agaricus", "Neoshadow", "Stealth Soldier", "Gigas Shadow",
        "Sniperwild", "Black Ballade",
        "Jet Balloon", "Unused 47", "Grand Ghost",
        "Destroyed Behemoth", "Arch Behemoth", "Sneak Army"
    ]
    obj.heartless_fm_dict = {
        "Shadow": 0x01,
        "Gigas Shadow": 0x2A,
        "Soldier": 0x00,
        "Stealth Soldier": 0x29,
        "Large Body": 0x04,
        "Red Nocturne": 0x0A,
        "Blue Rhapsody": 0x0B,
        "Yellow Opera": 0x0C,
        "Green Requiem": 0x0D,
        "Black Ballade": 0x2C,
        "Powerwild": 0x02,
        "Bouncywild": 0x03,
        "Sniperwild": 0x2B,
        "Air Solider": 0x0F,
        "Bandit": 0x08,
        "Fat Bandit": 0x05,
        "Pot Spider": 0x10,
        "Barrel Spider": 0x11,
        "Pot Scorpion": 0x12,
        "Search Ghost": 0x16,
        "Grand Ghost": 0x2F,
        "Sea Neon": 0x06,
        "Sheltering Zone": 0x07,
        "Screwdriver": 0x18,
        "Aquatank": 0x17,
        "Wight Knight": 0x13,
        "Gargoyle": 0x15,
        "Chimera": 0x19,
        "Pirate": 0x09,
        "Air Pirate": 0x14,
        "Battleship": 0x1A,
        "Jet Balloon": 0x2D,
        "Darkball": 0x1B,
        "Defender": 0x20,
        "Wyvern": 0x1E,
        "Wizard": 0x0E,
        "Behemoth": 0x1D,
        "Destroyed Behemoth": 0x30,
        "Arch Behemoth": 0x31,
        "Invisible": 0x1C,
        "Angel Star": 0x1F,
        "Neoshadow": 0x28,
        "White Mushroom": 0x21,
        "Black Fungus": 0x22,
        "Rare Truffle": 0x23,
        "Pink Agaricus": 0x27,
        "Sneak Army": 0x32,
        "Unused 37": 0x24,
        "Unused 38": 0x25,
        "Unused 39": 0x26,
        "Unused 47": 0x2E,
    }
    obj.summon_dict = {
        "Empty": 0xFF,
        "Dumbo": 0x00,
        "Bambi": 0x01,
        "Genie": 0x02,
        "Tinker Bell": 0x03,
        "Mushu": 0x04,
        "Simba": 0x05,
        "Bahamut": 0x06
    }
    # The value is the number of parts.
    obj.chronicles_dict = {
        "Sora's Story": 5,
        "Wonderland": 3,
        "Olympus Coliseum": 3,
        "Deep Jungle": 3,
        "Agrabah": 3,
        "Monstro": 3,
        "Hundred Acre Woods": 2,
        "Atlantica": 3,
        "Halloween Town": 3,
        "Neverland": 3,
    }
    # Byte index * 16 + bit index
    # Characters with multiple entry flags only have 1 set at a time.
    obj.journal_chars_1_dict = {
        # Page 1
        "Sora 1": 0x07,
        "Sora 2": 0x06,
        "Riku 1": 0x05,
        "Riku 2": 0x04,
        "Riku 3": 0x03,
        "Riku 4": 0x02,
        "Kairi 1": 0x01,
        "Kairi 2": 0x00,
        "Mickey Mouse": 0x17,
        "Donald Duck 1": 0x16,
        "Donald Duck 2": 0x15,
        "Goofy 1": 0x14,
        "Goofy 2": 0x13,
        "Minnie Mouse": 0x12,
        "Daisy Duck": 0x11,
        # Page 2
        "Pluto": 0x10,
        "Chip": 0x27,
        "Dale": 0x26,
        "Huey": 0x25,
        "Dewey": 0x24,
        "Louie": 0x23,
        "Merlin": 0x22,
        "Fairy Godmother": 0x21,
        # Page 3
        "Pongo": 0x20,
        "Perdita": 0x37,
        "99 Puppies": 0x36,
        "Brooms": 0x35,
        "Leon": 0x34,
        "Yuffie": 0x33,
        "Aerith": 0x32,
        "Cloud": 0x31,
        # Page 4
        "Sephiroth": 0x142,
        "Cid": 0x30,
        "Tidus": 0x47,
        "Selphie": 0x46,
        "Wakka": 0x45,
        "Moogles": 0x44,
        "Snow White": 0x42,
        "Cinderella": 0x41,
        # Page 5
        "Aurora": 0x40,
        "Bell": 0x57,
        "Beast": 0x56,
        "Maleficent 1": 0x55,
        "Maleficent 2": 0x54,
        "Maleficent 3": 0x53,
        "Dragon": 0x52,
        "Ansem 1": 0x43,
        "Ansem 2": 0x51,
        "?": 0x156,
    }
    obj.journal_chars_2_dict = {
        # Page 1
        "Dumbo": 0x50,
        "Bambi": 0x67,
        "Mushu": 0x66,
        "Simba": 0x65,
        "Alice 1": 0x64,
        "Alice 2": 0x63,
        "Queen of Hearts": 0x62,
        "Cards (Hearts)": 0x61,
        "Cards (Spades)": 0x60,
        # Page 2
        "White Rabbit": 0x77,
        "Chesire Cat": 0x76,
        "Doorknob": 0x75,
        "Hercules": 0x74,
        "Philoctetes": 0x73,
        "Hades 1": 0x72,
        "Hades 2": 0x71,
        "Cerberus": 0x70,
        "Rock Titan": 0x87,
        # Page 3
        "Ice Titan": 0x141,
        "Tarzan": 0x86,
        "Jane Porter": 0x85,
        "Clayton 1": 0x84,
        "Clayton 2": 0x83,
        "Terk": 0x82,
        "Kerchak": 0x81,
        "Kala": 0x80,
        "Sabor": 0x97,
        # Page 4
        "Aladdin 1": 0x96,
        "Aladdin 2": 0x95,
        "Genie 1": 0x94,
        "Genie 2": 0x93,
        "Jasmine 1": 0x92,
        "Jasmine 2": 0x140,
        "Jafar 1": 0x91,
        "Jafar 2": 0x90,
        "Jafar-Genie": 0xA7,
        "Abu": 0xA6,
        "Iago": 0xA5,
        "Carpet": 0xA4,
        # Page 5
        "Pinocchio 1": 0xA3,
        "Pinocchio 2": 0xA2,
        "Geppetto 1": 0xA1,
        "Geppetto 2": 0xA0,
        "Jiminy Cricket": 0xB7,
        "Ariel 1": 0xB6,
        "Ariel 2": 0xB5,
        "King Triton": 0xB4,
        "Ursula 1": 0xB3,
        "Ursula 2": 0xB2,
        "Sebastian": 0xB1,
        "Flounder": 0xB0,
        # Page 6
        "Jetsam": 0xC7,
        "Flotsam": 0xC6,
        "Jack Skellington": 0xC5,
        "Sally": 0xC4,
        "Oogie Boogie 1": 0xC3,
        "Oogie Boogie 2": 0xC2,
        "Dr. Finkelstein": 0xC1,
        "Zero": 0xC0,
        "Lock": 0xD7,
        # Page 7
        "Shock": 0xD6,
        "Barrel": 0xD5,
        "The Mayor": 0xD4,
        "Peter Pan": 0xD3,
        "Tinker Bell 1": 0xD2,
        "Tinker Bell 2": 0xD1,
        "Wendy": 0xD0,
        "Captain Hook 1": 0xE7,
        "Captain Hook 2": 0xE6,
        "Mr. Smee": 0xE5,
        # Page 8
        "The Crocodile": 0xE4,
        "Winnie the Pooh": 0xE3,
        "Piglet": 0xE2,
        "Tigger": 0xE1,
        "Owl": 0xE0,
        "Rabbit": 0xF7,
        "Eeyore": 0xF6,
        "Roo": 0xF5,
    }
    obj.journal_boss_dict = {
        "Darkside": 0x132,
        "Guard Armor": 0x131,
        "Red Armor": 0x161,
        "Opposite Armor": 0x130,
        "Trickmaster": 0x147,
        "Stealth Sneak": 0x146,
        "Pot Centipede": 0x145,
        "Parasite Cage": 0x144,
        "Kurt Zisa": 0x157,
        "Phantom": 0x143,
    }

def trinity_dicts(obj):
    obj.trinity_names = [
        "Trinity Jump",
        "Trinity Charge",
        "Trinity Ladder",
        "Trinity Push",
        "Trinity Detect",
    ]
    obj.trinity_dict_list = [
        {
            "Traverse Town: 1st District: At the World Exit": 0x06,
            "Traverse Town: 1st District: On the balcony": 0x05,
            "Traverse Town: Magician's Study": 0x450,
            "Traverse Town: 3rd District": 0x473,
            "Wonderland: Lotus Forest: 1": 0x25,
            "Wonderland: Lotus Forest: 2": 0x26,
            "Olympus Coliseum: Coliseum Gates: 1": 0x45,
            "Olympus Coliseum: Coliseum Gates: 2": 0x46,
            "Deep Jungle: Climbing Trees": 0x64,
            "Deep Jungle: Camp": 0x65,
            "Agrabah: Bazaar": 0x86,
            "Agrabah: Silent Chamber": 0x82,
            "Monstro: Chamber 5": 0xA3,
            "Monstro: Throat": 0xA4,
            "Monstro: Mouth": 0xA5,
            "Hollow Bastion: Dungeon": 0xF5,
            "Hollow Bastion: Great Crest": 0xF6,
        },
        {
            "Traverse Town: 1st District": 0x447,
            "Traverse Town: 2nd District": 0x454,
            "Traverse Town: Alleyway": 0x455,
            "Agrabah: Treasure Room": 0x83,
            "Halloween Town: Oogie's Manor": 0xC6,
            "Hollow Bastion: Entrance Hall": 0x107,
        },
        {
            "Traverse Town: Accessory Shop": 0x463,
            "Wonderland: Bizarre Room": 0x23,
            "Wonderland: Rabbit Hole": 0x24,
            "Olympus Coliseum: Coliseum Gates": 0x43,
            "Deep Jungle: Treetop": 0x63,
            "Agrabah: Agrabah: Storage": 0x85,
            "Monstro: Mouth": 0xA6,
            "Neverland: Ship: Cabin": 0xE0,
            "Hollow Bastion: Library": 0x106,
        },
        {
            "Traverse Town: Mystical House": 0x16,
            # Has special treatment since its out of bounds.
            "Olympus Coliseum: Coliseum: Lobby": 0x1A40,
            "Agrabah: Cave: Hall": 0x84,
            "Neverland: Ship: Hold": 0xE1,
        },
        {
            "Traverse Town: Secret Waterway": 0x07,
            "Wonderland: Lotus Forest": 0x27,
            "Olympus Coliseum: Coliseum Gates": 0x42,
            "Deep Jungle: Cavern of Hearts": 0x67,
            "Agrabah: Cave: Entrance": 0x87,
            "Monstro: Chamber 6": 0xA7,
            "Atlantica: Triton's Palace": 0x137,
            "Halloween Town: Moonlight Hill": 0xC7,
            "Neverland: Pirate Ship": 0xE7,
            "Hollow Bastion: Rising Falls": 0xF7,
        },
    ]

def gummi_dicts(obj):
    obj.gummi_block_cockpit_dict = {
        "Cure-G": 0x00,
        "Curaga-G": 0x01,
        "Life-G": 0x02,
        "Full-Life-G": 0x03,
    }
    obj.gummi_block_engine_dict = {
        "Fire-G": 0x04,
        "Fira-G": 0x05,
        "Firaga-G": 0x06,
        "Flare-G": 0x07,
        "Holy-G": 0x08,
    }
    obj.gummi_block_armor_dict = {
        "Protect-G 1": 0x09,
        "Protect-G 2": 0x0A,
        "Protect-G 3": 0x0B,
        "Protect-G 4": 0x0C,
        "Protect-G 5": 0x0D,
        "Protect-G 6": 0x0E,
        "Protect-G 7": 0x0F,
        "Protect-G 8": 0x10,
        "Shell-G 1": 0x11,
        "Shell-G 2": 0x12,
        "Shell-G 3": 0x13,
        "Shell-G 4": 0x14,
        "Shell-G 5": 0x15,
        "Shell-G 6": 0x16,
        "Shell-G 7": 0x17,
        "Shell-G 8": 0x18,
        "Dispel-G 1": 0x19,
        "Dispel-G 2": 0x1A,
        "Dispel-G 3": 0x1B,
        "Dispel-G 4": 0x1C,
        "Dispel-G 5": 0x1D,
        "Dispel-G 6": 0x1E,
        "Dispel-G 7": 0x1F,
        "Dispel-G 8": 0x20,
    }
    obj.gummi_block_wing_dict = {
        "Aerora-G 1": 0x21,
        "Aerora-G 2": 0x22,
        "Aeroga-G 1": 0x23,
        "Aeroga-G 2": 0x24,
        "Tornado-G 1": 0x25,
        "Tornado-G 2": 0x26,
        "Float-G 1": 0x27,
        "Float-G 2": 0x28,
        "Aero-G 1": 0x29,
        "Aero-G 2": 0x2A,
        "Aero-G 3": 0x2B,
    }
    obj.gummi_block_special_dict = {
        "Drain-G 1": 0x2C,
        "Drain-G 2": 0x2D,
        "Osmose-G 1": 0x2E,
        "Osmose-G 2": 0x2F,
        "Transform-G": 0x30,
        "Warp-G": 0x31,
        "Scan-G 1": 0x32,
        "Scan-G 2": 0x33,
        "Haste-G": 0x34,
        "Haste2-G": 0x35,
        "Shield-G": 0x36,
        "Shield2-G": 0x37,
        "Esuna-G 1": 0x38,
        "Esuna-G 2": 0x39,
    }
    obj.gummi_block_weapon_dict = {
        "Thunder-G": 0x3A,
        "Thundara-G": 0x3B,
        "Thundaga-G": 0x3C,
        "Comet-G": 0x3D,
        "Meteor-G": 0x3E,
        "Ultima-G": 0x3F,
    }
    obj.gummi_block_upgrade_dict = {
        "Spray": 0x40,
        "Palette": 0x41,
        "SYS.UP1": 0x42,
        "SYS.UP2": 0x43,
        "COM.LV1": 0x44,
        "COM.LV2": 0x45,
        "COM.LV3": 0x46,
    }
    obj.gummi_blueprint_dict = {
        "Kingdom": 0x47,
        "Hyperion": 0x48,
        "Geppetto": 0x49,
        "Cid": 0x4A,
        "Leon": 0x4B,
        "Yuffie": 0x4C,
        "Aerith": 0x4D,
        "Cactuar": 0x4E,
        "Chocobo": 0x4F,
        "Cindy": 0x50,
        "Shiva": 0x51,
        "Lamia": 0x52,
        "Sandy": 0x53,
        "Sylph": 0x54,
        "Carbuncle": 0x55,
        "Mindy": 0x56,
        "Goblin": 0x57,
        "Bomb": 0x58,
        "Remora": 0x59,
        "Ahriman": 0x5A,
        "Imp": 0x5B,
        "Siren": 0x5C,
        "Stingray": 0x5D,
        "Catoblepas": 0x5E,
        "Adamant": 0x5F,
        "Serpent": 0x60,
        "Ifrit": 0x61,
        "Odin": 0x62,
        "Atomos": 0x63,
        "Golem": 0x64,
        "Diablos": 0x65,
        "Deathguise": 0x66,
        "Typhoon": 0x67,
        "Alexander": 0x68,
        "Leviathan": 0x69,
        "Ramuh": 0x6A,
        "Omega": 0x6B,
    }
    obj.gummi_blueprint_fm_dict = {
        "Moogle": 0x6C,
        "Valefor": 0x6D,
        "Pupu": 0x6E,
        "Cerberus": 0x6F,
        "Tonberry": 0x70,
        "Pandaemonium": 0x71,
        "Ixion": 0x72,
        "Gilgamesh": 0x73,
        "Phoenix": 0x74,
        "Eden": 0x75,
        "Bahamut": 0x76,
    }
    obj.gummi_block_design_dict = {
        "Wheel-G": 0x80,
        "Fang-G": 0x81,
        "Horn-G": 0x82,
        "Angel-G": 0x83,
        "Dark-G": 0x84,
        "Shoes-G": 0x85,
        "Rock-G 1": 0x86,
        "Rock-G 2": 0x87,
        "Scissors-G 1": 0x88,
        "Scissors-G 2": 0x89,
        "Paper-G 1": 0x8A,
        "Paper-G 2": 0x8B,
        "Crown-G": 0x8C,
        "Drill-G": 0x8D,
        "Caterpillar-G 1": 0x8E,
        "Caterpillar-G 2": 0x8F,
    }
    obj.gummi_max_list = [
        # Cockpits
        1, 1,
        1, 1,
        # Engines
        6, 6, 4,
        4, 2,
        # Armors
        99, 99, 99, 30, 30, 10, 10, 10,
        99, 99, 99, 20, 20, 8, 8, 8,
        99, 99, 99, 10, 10, 6, 6, 6,
        # Wings
        30, 30,
        20, 20,
        10, 10,
        10, 10,
        99, 99, 99,
        # Specials
        4, 4,
        2, 2,
        1, 1,
        2, 2,
        2, 2,
        1, 1,
        6, 10,
        # Weapons
        10, 8, 6,
        8, 6, 4,
        # Upgrades
        1, 1,
        1, 1,
        1, 1, 1,
        # All blueprints have 1 max.
    ]
