from .dicts import *


def dicts(obj):
    main_dicts(obj)
    customize_dicts(obj)
    inventory_dicts(obj)
    world_dicts(obj)
    journal_dicts(obj)
    trinity_dicts(obj)
    minigame_dicts(obj)
    gummi_dicts(obj)
    treasure_dicts(obj)

def main_dicts(obj):
    obj.character_dict = {
        "Sora": 0,
        "Donald": 1,
        "Goofy": 2,
        "Tarzan": 3,
        "Winnie the Pooh": 4,
        "Aladdin": 5,
        "Ariel": 6,
        "Jack Skellington": 7,
        "Peter Pan": 8,
        "Beast": 9,
        "None": 255
    }
    obj.ability_dict = {
        "Empty": 0x00,
        "High Jump": 0x01,
        "Mermaid Kick": 0x02,
        "Glide": 0x03,
        "Superglide": 0x04,
        "Treasure Magnet": 0x05,
        "Combo Plus": 0x06,
        "Air Combo Plus": 0x07,
        "Critical Plus": 0x08,
        "Second Wind": 0x09,
        "Scan": 0x0A,
        "Sonic Blade": 0x0B,
        "Ars Arcanum": 0x0C,
        "Strike Raid": 0x0D,
        "Ragnarok": 0x0E,
        "Trinity Limit": 0x0F,
        "Cheer": 0x10,
        "Vortex": 0x11,
        "Aerial Sweep": 0x12,
        "Counterattack": 0x13,
        "Blitz": 0x14,
        "Guard": 0x15,
        "Dodge Roll": 0x16,
        "MP Haste": 0x17,
        "MP Rage": 0x18,
        "Second Chance": 0x19,
        "Berserk": 0x1A,
        "Jackpot": 0x1B,
        "Lucky Strike": 0x1C,
        "Charge": 0x1D,
        "Rocket": 0x1E,
        "Tornado": 0x1F,
        "MP Gift": 0x20,
        "Raging Boar": 0x21,
        "Asp’s Bite": 0x22,
        "Healing Herb": 0x23,
        "Wind Armor": 0x24,
        "Crescent": 0x25,
        "Sandstorm": 0x26,
        "Applause!": 0x27,
        "Blazing Fury": 0x28,
        "Icy Terror": 0x29,
        "Bolts of Sorrow": 0x2A,
        "Ghostly Scream": 0x2B,
        "Hummingbird": 0x2C,
        "Time-Out": 0x2D,
        "Storm’s Eye": 0x2E,
        "Ferocious Lunge": 0x2F,
        "Furious Bellow": 0x30,
        "Spiral Wave": 0x31,
        "Thunder Potion": 0x32,
        "Cure Potion": 0x33,
        "Aero Potion": 0x34,
        # FM exclusives
        "Slapshot": 0x35,
        "Sliding Dash": 0x36,
        "Hurricane Blast": 0x37,
        "Ripple Drive": 0x38,
        "Stun Impact": 0x39,
        "Gravity Break": 0x3A,
        "Zantetsuken": 0x3B,
        "Tech Boost": 0x3C,
        "Encounter Plus": 0x3D,
        "Leaf Bracer": 0x3E,
        "Evolution": 0x3F,
        # Remix exclusives
        "EXP Zero": 0x40,
        "Combo Master": 0x41
    }

def customize_dicts(obj):
    obj.magicnames = ["Fire", "Blizzard", "Thunder", "Cure", "Gravity", "Stop", "Aero"]
    obj.magicnames2 = ["Fira", "Blizzara", "Thundara", "Cura", "Gravira", "Stopra", "Aerora"]
    obj.magicnames3 = ["Firaga", "Blizzaga", "Thundaga", "Curaga", "Graviga", "Stopga", "Aeroga"]
    obj.summon_dict = {
        "Empty": 0xFF,
        "Dumbo": 0x00,
        "Bambi": 0x01,
        "Genie": 0x02,
        "Tinker Bell": 0x03,
        "Mushu": 0x04,
        "Simba": 0x05,
        "Bahamut": 0x06
    }
    obj.customize_dict = {
        "Donald": {
            "Regular Attacks": {
                "offset": 0x16804,
                "bit": 0,
                "dict": 0,
            },
            "Offensive Magic": {
                "offset": 0x16804,
                "bit": 6,
                "dict": 0,
            },
            "Defensive Magic": {
                "offset": 0x16805,
                "bit": 0,
                "dict": 0,
            },
            "Advanced Magic": {
                "offset": 0x16805,
                "bit": 2,
                "dict": 0,
            },
            "HP items": {
                "offset": 0x16804,
                "bit": 2,
                "dict": 1,
            },
            "MP items": {
                "offset": 0x16804,
                "bit": 4,
                "dict": 1,
            },
        },
        "Goofy": {
            "Regular Attacks": {
                "offset": 0x16808,
                "bit": 0,
                "dict": 0,
            },
            "Support Actions": {
                "offset": 0x16809,
                "bit": 4,
                "dict": 0,
            },
            "Shield Techniques": {
                "offset": 0x16809,
                "bit": 6,
                "dict": 0,
            },
            "Special Attacks": {
                "offset": 0x1680A,
                "bit": 0,
                "dict": 0,
            },
            "HP items": {
                "offset": 0x16808,
                "bit": 2,
                "dict": 1,
            },
            "MP items": {
                "offset": 0x16808,
                "bit": 4,
                "dict": 1,
            },
        },
        "Tarzan": {
            "Regular Attacks": {
                "offset": 0x1680C,
                "bit": 0,
                "dict": 0,
            },
            "Defensive Moves": {
                "offset": 0x1680D,
                "bit": 6,
                "dict": 0,
            },
            "Special Attacks": {
                "offset": 0x1680E,
                "bit": 0,
                "dict": 0,
            },
            "HP items": {
                "offset": 0x1680C,
                "bit": 2,
                "dict": 1,
            },
            "MP items": {
                "offset": 0x1680C,
                "bit": 4,
                "dict": 1,
            },
        },
        "Winnie the Pooh": {
            "Regular Attacks": {
                "offset": 0x16810,
                "bit": 0,
                "dict": 0,
            },
            "Offensive Magic": {
                "offset": 0x16810,
                "bit": 6,
                "dict": 0,
            },
            "Defensive Magic": {
                "offset": 0x16811,
                "bit": 0,
                "dict": 0,
            },
            "Advanced Magic": {
                "offset": 0x16811,
                "bit": 2,
                "dict": 0,
            },
            "Support Actions": {
                "offset": 0x16811,
                "bit": 4,
                "dict": 0,
            },
            "Defensive Moves": {
                "offset": 0x16811,
                "bit": 6,
                "dict": 0,
            },
            "Special Attacks": {
                "offset": 0x16812,
                "bit": 0,
                "dict": 0,
            },
            "HP items": {
                "offset": 0x16810,
                "bit": 2,
                "dict": 1,
            },
            "MP items": {
                "offset": 0x16810,
                "bit": 4,
                "dict": 1,
            },
        },
        "Aladdin": {
            "Regular Attacks": {
                "offset": 0x16814,
                "bit": 0,
                "dict": 0,
            },
            "Special Attacks": {
                "offset": 0x16816,
                "bit": 0,
                "dict": 0,
            },
            "HP items": {
                "offset": 0x16814,
                "bit": 2,
                "dict": 1,
            },
            "MP items": {
                "offset": 0x16814,
                "bit": 4,
                "dict": 1,
            },
        },
        "Ariel": {
            "Regular Attacks": {
                "offset": 0x16818,
                "bit": 0,
                "dict": 0,
            },
            "Defensive Moves": {
                "offset": 0x16819,
                "bit": 6,
                "dict": 0,
            },
            "Special Attacks": {
                "offset": 0x1681A,
                "bit": 0,
                "dict": 0,
            },
            "HP items": {
                "offset": 0x16818,
                "bit": 2,
                "dict": 1,
            },
            "MP items": {
                "offset": 0x16818,
                "bit": 4,
                "dict": 1,
            },
        },
        "Jack Skellington": {
            "Regular Attacks": {
                "offset": 0x1681C,
                "bit": 0,
                "dict": 0,
            },
            "Special Attacks": {
                "offset": 0x1681E,
                "bit": 0,
                "dict": 0,
            },
            "HP items": {
                "offset": 0x1681C,
                "bit": 2,
                "dict": 1,
            },
            "MP items": {
                "offset": 0x1681C,
                "bit": 4,
                "dict": 1,
            },
        },
        "Peter Pan": {
            "Regular Attacks": {
                "offset": 0x16820,
                "bit": 0,
                "dict": 0,
            },
            "Defensive Moves": {
                "offset": 0x16821,
                "bit": 6,
                "dict": 0,
            },
            "Special Attacks": {
                "offset": 0x16822,
                "bit": 0,
                "dict": 0,
            },
            "HP items": {
                "offset": 0x16820,
                "bit": 2,
                "dict": 1,
            },
            "MP items": {
                "offset": 0x16820,
                "bit": 4,
                "dict": 1,
            },
        },
        "Beast": {
            "Regular Attacks": {
                "offset": 0x16824,
                "bit": 0,
                "dict": 0,
            },
            "Special Attacks": {
                "offset": 0x16826,
                "bit": 0,
                "dict": 0,
            },
            "HP items": {
                "offset": 0x16824,
                "bit": 2,
                "dict": 1,
            },
            "MP items": {
                "offset": 0x16824,
                "bit": 4,
                "dict": 1,
            },
        },
        # Possible pattern template
        "Character": {
            "Regular Attacks": {
                "offset": 0,
                "bit": 0,
                "dict": 0,
            },
            "HP items": {
                "offset": 0,
                "bit": 2,
                "dict": 1,
            },
            "MP items": {
                "offset": 0,
                "bit": 4,
                "dict": 1,
            },
            "Offensive Magic": {
                "offset": 0,
                "bit": 6,
                "dict": 0,
            },
            "Defensive Magic": {
                "offset": 1,
                "bit": 0,
                "dict": 0,
            },
            "Advanced Magic": {
                "offset": 1,
                "bit": 2,
                "dict": 0,
            },
            "Support Actions": {
                "offset": 1,
                "bit": 4,
                "dict": 0,
            },
            "Shield Techniques": {
                "offset": 1,
                "bit": 6,
                "dict": 0,
            },
            "Defensive Moves": {
                "offset": 1,
                "bit": 6,
                "dict": 0,
            },
            "Special Attacks": {
                "offset": 2,
                "bit": 0,
                "dict": 0,
            },
        },
    }
    obj.customize_list = [
        {
            "Constantly": 2,
            "Frequently": 1,
            "Occasionally": 0,
        },
        {
            "Immediately": 2,
            "Frequently": 1,
            "Only in emergency": 0,
        },
    ]

def world_dicts(obj):
    obj.world_dict = {
        0x00: "Dive to the Heart",
        0x01: "Destiny Islands",
        0x02: "Disney Castle",
        0x03: "Traverse Town",
        0x04: "Wonderland",
        0x05: "Deep Jungle",
        0x06: "Hundred Acre Woods",
        #0x07: "Unused 0x07",
        0x08: "Agrabah",
        0x09: "Atlantica",
        0x0A: "Halloween Town",
        0x0B: "Olympus Coliseum",
        0x0C: "Monstro",
        0x0D: "Neverland",
        #0x0E: "Unused 0x0E",
        0x0F: "Hollow Bastion",
        0x10: "End of the World"
    }
    obj.world_status_dict = {
        "Undiscovered": 0,
        "Hidden": 1,
        "Unknown": 2,
        "Discovered": 3,
        "Completed": 4,
    }
    obj.landingpoints_dict = {
        "Traverse Town": [
            0x00,
            "1st District",
            "Accessory Shop",
            "Magician's Study",
        ],
        "Wonderland": [
            0x01,
            "Rabbit Hole",
            "Queen's Castle",
        ],
        "Olympus Coliseum": [
            0x02,
            "Coliseum Gates",
        ],
        "Deep Jungle": [
            0x03,
            "Camp: Tent",
            "Jungle: Tunnel",
            "Jungle: Vines",
        ],
        "Agrabah": [
            0x04,
            "Agrabah: Main Street",
            "Agrabah: Storage",
            "Aladdin's House",
            "Treasure Room",
            "Dark Chamber",
        ],
        "Monstro": [
            0x0A,
        ],
        "Atlantica": [
            0x06,
            "Tranquil Grotto",
            "Cavern Nook",
            "Triton's Throne",
        ],
        "Halloween Town": [
            0x05,
            "Guillotine Gate",
        ],
        "Neverland": [
            0x07,
            "Ship: Hold",
            "Ship: Cabin",
            "Clock Tower",
            "Clock Tower",
        ],
        "Hollow Bastion": [
            0x08,
            "Rising Falls",
            "Library",
            "Waterway",
            "Castle Chapel",
        ],
        "End of the World": [
            0x09,
            "Gate to the Dark",
            "World Terminus",
            "Final Rest",
            "Final Rest",
        ],
        "Blue Warp Hole": [
            0x0C,
        ],
        "Orange Warp Hole": [
            0x0D,
        ],
        "Purple Warp Hole": [
            0x0E,
        ],
        "Pirate Ship": [
            0x0B,
        ],
    }
    # Oh boy, I had to stitch together
    # the vanilla and FM RA code notes for this
    # They don't seem to be bit flags
    obj.world_progress_dict = {
        "Gummi Path": {
            "index": 0x00,
        },
        "Dive to the Heart": {
            "index": 0x01,
            "Start": 0x00,
            "Before 1st Dream Weapon": 0x04,
            "Before 2nd Dream Weapon": 0x07,
            "After Dream Weapon selection": 0x0A,
            "Unknown": 0x56,
        },
        "Destiny Islands": {
            "index": 0x02,
            "Start": 0x00,
            "Start 2": 0x14,
            "Cave cutscene": 0x21,
            "Day 2 ended": 0x17,
            "Shadows swarm the island": 0x1E,
            "Kingdom Key obtained": 0x24,
        },
        "Disney Castle": {
            "index": 0x03,
            "Start": 0x00,
            "Start 2": 0x01,
            "Donald & Goofy cutscene": 0x04,
        },
        "Traverse Town": {
            "index": 0x04,
            "Start": 0x00,
            "After waking up": 0x01,
            "After Leon fight": 0x1A,
            "After ?": 0x23,
            "Guard Armor fight": 0x28,
            "After Guard Armor": 0x2A,
            "1st visit complete": 0x3C,
            "Earthshine obtained": 0x3E,
            "Old book obtained": 0x42,
            "Old book delivered": 0x4A,
            "Maleficent & Riku cutscene": 0x4E,
            "Neverland Navi-G to Cid": 0x5C,
            "Kairi's grandmother flashback": 0x5E,
            "After the flashback": 0x60,
            "Transform-G obtained": 0x64,
            "After Hollow Bastion": 0x6E,
            "Navi-G in the Secret Waterway": 0x78,
            "Oathkeeper obtained": 0x8C,
            "Navi-G installed": 0x96,
        },
        "Deep Jungle": {
            "index": 0x05,
            "Start": 0x00,
            "Arrived": 0x01,
            "1st cutscene": 0x0A,
            "Sabor defeated": 0x0D,
            "Tarzan to the rescue": 0x10,
            "Donald & Goofy cutscene": 0x12,
            "Regain control": 0x14,
            "Donald & Goofy joins": 0x17,
            "Talk to Jane after all slides obtained": 0x1A,
            "All slides watched, enter Clayton": 0x20,
            "Tarzan & Kerchak cutscene": 0x23,
            "Donald scares Clayton": 0x28,
            "Clayton leaves": 0x2B,
            "Heartless attack": 0x32,
            "All gorillas rescued": 0x35,
            "Enter tent after all gorillas rescued": 0x37,
            "Leave tent after all gorillas rescued": 0x39,
            "Sabor attacks again": 0x3C,
            "2nd Sabor fight start": 0x3F,
            "Sabor 2 defeated": 0x42,
            "Jane gets kidnapped": 0x44,
            "Rescue Jane fight start": 0x46,
            "Rescue Jane fight end": 0x47,
            "Jane rescued": 0x48,
            "Before Clayton phase 1": 0x50,
            "Before Clayton phase 2": 0x53,
            "Clayton & Stealth Sneak defeated": 0x56,
            "Tarzan yeets Sora": 0x59,
            "Keyhole sealed": 0x5C,
            "Maleficent cutscene": 0x5F,
            "Red Trinity learned; Visit complete": 0x6E,
        },
        "Olympus Coliseum": {
            "index": 0x06,
            "Start": 0x00,
            "Arrived": 0x01,
            "Talk to Phil": 0x04,
            "Talk to Phil after pushing the pillar": 0x07,
            "Training complete": 0x0A,
            "Thunder obtained": 0x0D,
            "Entry Pass obtained": 0x10,
            "Talk to Phil with Entry Pass": 0x13,
            "After Preliminaries 1": 0x16,
            "After Preliminaries 3": 0x19,
            "Hades & Cloud cutscene": 0x1C,
            "Cloud defeated": 0x22,
            "Cerberus defeated": 0x25,
            "Hero License obtained": 0x28,
            "Hades & Maleficent cutscene": 0x32,
            # This is missing from RA
            "Keyhole sealed": 0x3C,
        },
        "Wonderland": {
            "index": 0x07,
            "Start": 0x00,
            "1st cutscene": 0x01,
            "2nd cutscene": 0x04,
            "Shrinking unlocked": 0x07,
            "Alice's trial": 0x0D,
            "Presenting the evidences": 0x11,
            "Tower fight": 0x21,
            "Trickmaster fight start": 0x2B,
            "Trickmaster defeated": 0x2E,
            "Keyhole sealed": 0x30,
            "Visit complete": 0x32,
        },
        "Agrabah": {
            "index": 0x08,
            "Start": 0x00,
            "Arrived": 0x0A,
            "Freed Carpet": 0x17,
            "Rescuing Aladdin": 0x1E,
            "Aladdin joins the party": 0x24,
            "Genie reminiscing about the keyhole": 0x27,
            "Pot Centipede defeated": 0x35,
            "Cave of Wonders fight start": 0x3C,
            "Cave of Wonders defeated": 0x3F,
            "Sora meets Maleficent cutscene": 0x46,
            "Jafar defeated": 0x49,
            "Moving towards Jasmine": 0x50,
            "Jafar-Genie defeated": 0x53,
            "Sealing Jafar-Genie": 0x5A,
            "Escape from the Cave of Wonders": 0x5D,
            "Aladdin sets Genie free": 0x64,
            "Hall of Villains cutscene": 0x6E,
            "Three Wishes obtained": 0x78,
            "Visit complete": 0x82,
            "Kurt Zisa defeated": 0xA0, # I found this
        },
        "Monstro": {
            "index": 0x09,
            "Start": 0x00,
            "Swallowed": 0x0D,
            "Pinocchio throwing stuff at us": 0x14,
            "Meeting Geppetto": 0x17,
            "Meeting Riku": 0x1A,
            "Riku and Maleficent cutscene": 0x1E,
            "Pinocchio gets kidnapped": 0x28,
            "Parasite Cage 1 fight starts": 0x2B,
            "Parasite Cage 1 defeated": 0x2E,
            "Water level raising": 0x32,
            "Parasite Cage 2 fight starts": 0x3C,
            "Parasite Cage 2 defeated": 0x3F,
            "Riku can control the Heartless now": 0x46,
        },
        "Atlantica": {
            "index": 0x0A,
            "Start": 0x00,
            "Arrived": 0x01,
            "Swimming tutorial": 0x04,
            "Fighting some Heartless": 0x07,
            "Ariel joins the party": 0x0A,
            "Title card appeared": 0x0D,
            "Meeting King Triton": 0x14,
            "Ariel's Grotto cutscene": 0x17,
            "Ursula cutscene": 0x21,
            "The shark breaks the window": 0x28,
            "Crystal Trident obtained": 0x32,
            "Triton destroys the Crystal Trident": 0x3C,
            "Ursula manipulates Ariel": 0x3F,
            "Ariel steals the trident": 0x42,
            "Ursula steals the trident": 0x46,
            "Press the switch to move the rock": 0x49,
            "Ursula I fight starts": 0x50,
            "Ursula I defeated": 0x53,
            "Ursula II fight starts": 0x5A,
            "Ursula II defeated": 0x5D,
            "Ursula dies": 0x60,
            "Keyhole sealed; Crabclaw obtained": 0x64,
            "Visit complete": 0x78,
        },
        "Unknown": {
            "index": 0x0B,
            "Start": 0x00,
        },
        "Halloween Town": {
            "index": 0x0C,
            "Start": 0x00,
            "Title Card appears": 0x01,
            "Meeting the peaceful Heartless": 0x04,
            "Meeting Jack": 0x07,
            "Artificial heart cutscene": 0x0A,
            "Missing ingredient": 0x0F,
            "Heartless are themselves again": 0x12,
            "Forget-Me-Not obtained": 0x1E,
            "Enter Lock, Shock and Barrel": 0x21,
            "Now you need a surprise": 0x28,
            "Oogie Boogie scheming": 0x2B,
            "Jack-In-The-Box obtained": 0x32,
            "Artificial heart got stolen": 0x35,
            "Zero on track": 0x38,
            "The trio crosses the hill": 0x3F,
            "Enterring Oogie's Manor": 0x46,
            "The trio drops off the artificial heart": 0x50,
            "Lock, Shock, Barrel defeated": 0x53,
            "Oogie Boogie eats the artificial heart": 0x5C,
            "Oogie Boogie defeated": 0x62,
            "Oogie's Manor transformed": 0x64,
            "Keyhole sealed": 0x6A,
            "Pumpkinhead obtained": 0x6E,
            "Visit complete": 0x78,
        },
        "Neverland": {
            "index": 0x0D,
            "Start": 0x00,
            "Riku can control the Heartless now": 0x04,
            "Title Card appears": 0x0A,
            "Riku creates Anti Sora": 0x14,
            "Going through the dark pathway": 0x17,
            "1st taste of pixie dust": 0x1E,
            "Riku ordering Captain Hook around": 0x28,
            "Anti Sora fight starts": 0x32,
            "Anti Sora defeated": 0x35,
            "Peter Pan leaves with Wendy": 0x38,
            "Sora learns how to fly": 0x3C,
            "Sora learned how to fly": 0x3F,
            "Heartless before Hook defeated": 0x46,
            "Captain Hook fight starts": 0x50,
            "Captain Hook defeated": 0x53,
            "Ars Arcanum learned": 0x56,
            "Sora thinks about Kairi": 0x5A,
            "Keyhole sealed": 0x64,
            "Flashback": 0x6A,
            "Tinker Bell, Fairy Harp, Glide": 0x6E,
            "Visit complete": 0x78,
            # Missing from RA
            "Phantom defeated": 0x96,
        },
        "Hollow Bastion": {
            "index": 0x0E,
            "Start": 0x00,
            "Riku gets powered up": 0x01,
            "Kairi' grandmother flashback": 0x0A,
            "Arrived": 0x14,
            "Riku takes the Keyblade": 0x1E,
            "Princesses of Heart reveal the keyhole": 0x28,
            "White Trinity learned": 0x32,
            "Ansem possesses Riku": 0x46,
            "Keyblade of Hearts": 0x50,
            "Maleficent defeated": 0x5A,
            "Dragon Maleficent defeated": 0x6E,
            "Sora transformed": 0x82,
            "Donald and Goofy runs away": 0x8C,
            "Donald and Goofy notice Shadow Sora": 0x96,
            "Sora gains a new body": 0xA0,
            "Second visit start": 0xAA,
            "Behemoth defeated": 0xB9,
            "FF characters cutscene": 0xBE,
            "Keyhole sealed": 0xC3,
        },
        "End of the World": {
            "index": 0x0F,
            "Start": 0x00,
            "Title Card appears": 0x01,
            # May have more here
            "Chernabog fight starts": 0x32,
            "Chernabog defeated": 0x33,
            # Post Final Rest progress
            "Back on Destiny Islands": 0x5A,
            "Ansem I fight starts": 0x64,
            "Ansem I defeated": 0x66,
            "Separated from Donald and Goofy": 0x6E,
            "Goofy rescued": 0x93,
            "World of Chaos defeated": 0x9B,
        },
        "Traverse Town 2": {
            "index": 0x12,
            "Start": 0x00,
            "Opposite Armor fight start": 0x0A,
            "Opposite Armor defeated": 0x14,
            "Keyhole sealed": 0x1E,
        },
    }
