# Backbone generated by Copilot but JP is by me based on that.
# Control codes from Crazycatz00's String Mapper
# String Mapper compatible

import codecs

decode_table = {0x00: "\x00",
                0x01: " ",
                0x02: "\n", # the encode table will include Crazycatz00's {lf}
                # 0x08 will be handled in the functions
                # 0x08 is the color control code
                # color is RGBA so 0x08 + 4 bytes
                # button prompts 0x09 and a second byte
                0x0900: "{controller:squ}",
                0x0901: "{controller:tri}",
                0x0902: "{controller:x}",
                0x0903: "{controller:o}",
                0x0904: "{controller:analog}",
                0x0905: "{controller:arrows}",
                0x0906: "{controller:l1}",
                0x0907: "{controller:l2}",
                0x0908: "{controller:r1}",
                0x0909: "{controller:r2}",
                0x20: "—",
                0x21: "0",
                0x22: "1",
                0x23: "2",
                0x24: "3",
                0x25: "4",
                0x26: "5",
                0x27: "6",
                0x28: "7",
                0x29: "8",
                0x2a: "9",
                0x2b: "A",
                0x2c: "B",
                0x2d: "C",
                0x2e: "D",
                0x2f: "E",
                0x30: "F",
                0x31: "G",
                0x32: "H",
                0x33: "I",
                0x34: "J",
                0x35: "K",
                0x36: "L",
                0x37: "M",
                0x38: "N",
                0x39: "O",
                0x3a: "P",
                0x3b: "Q",
                0x3c: "R",
                0x3d: "S",
                0x3e: "T",
                0x3f: "U",
                0x40: "V",
                0x41: "W",
                0x42: "X",
                0x43: "Y",
                0x44: "Z",
                0x45: "a",
                0x46: "b",
                0x47: "c",
                0x48: "d",
                0x49: "e",
                0x4a: "f",
                0x4b: "g",
                0x4c: "h",
                0x4d: "i",
                0x4e: "j",
                0x4f: "k",
                0x50: "l",
                0x51: "m",
                0x52: "n",
                0x53: "o",
                0x54: "p",
                0x55: "q",
                0x56: "r",
                0x57: "s",
                0x58: "t",
                0x59: "u",
                0x5a: "v",
                0x5b: "w",
                0x5c: "x",
                0x5d: "y",
                0x5e: "z",
                0x5f: "!",
                0x60: "?",
                0x61: "&",
                0x62: "%",
                0x63: "+",
                0x64: "{-}",
                0x65: "{mX}",
                0x66: "/",
                0x67: "*",
                0x68: ".",
                0x69: ",",
                0x6a: "・",
                0x6b: ":",
                0x6c: ";",
                0x6d: "…",
                0x6e: "-",
                0x6f: "ー",
                0x70: "~",
                0x71: "'",
                0x72: "“",
                0x73: "{゛b}",
                0x74: "(",
                0x75: ")",
                0x76: "[",
                0x77: "]",
                0x78: "<",
                0x79: ">",
                0x7a: "★",
                0x7b: "☆",
                0x7c: "↑",
                0x7d: "↓",
                0x7e: "→",
                0x7f: "←",
                0x80: "●",
                0x81: "■",
                0x82: "{iPotion}",
                0x83: "{iTent}",
                0x84: "{iGem}",
                0x85: "{iAbility}",
                0x86: "{iKey}",
                0x87: "{iStaff}",
                0x88: "{iShield}",
                0x89: "{iRing}",
                0x8a: "{iHat}",
                0x8b: "{iMickey}",
                0x8c: "○",
                0x8d: "×",
                0x8e: "△",
                0x8f: "□",
                0x90: "▲",
                0x91: "▼",
                0x92: "►",
                0x93: "◄",
                0x94: "{iGummi0}",
                0x95: "{iGummi1}",
                0x96: "{iGummi2}",
                0x97: "{iGummi3}",
                0x98: "{iGummi4}",
                0x99: "{iGummi5}",
                0x9a: "{iGummi6}",
                0x9b: "{iGummi7}",
                0x9c: "{iGummi8}",
                0x9d: "{iGummi9}",
                0xa9: "®",
                0xc4: "{III}",
                0xc5: "{VII}",
                0xc6: "{VIII}",
                0xc7: "{X}",
                0xc8: "Œ",
                0xc9: "œ",
                0xca: "¡",
                0xcb: "¿",
                0xcc: "À",
                0xcd: "Á",
                0xce: "Â",
                0xcf: "Ä",
                0xd0: "Ç",
                0xd1: "È",
                0xd2: "É",
                0xd3: "Ê",
                0xd4: "Ë",
                0xd5: "Ì",
                0xd6: "Í",
                0xd7: "Î",
                0xd8: "Ï",
                0xd9: "Ñ",
                0xda: "Ò",
                0xdb: "Ó",
                0xdc: "Ô",
                0xdd: "Ö",
                0xde: "Ù",
                0xdf: "Ú",
                0xe0: "Û",
                0xe1: "Ü",
                0xe2: "ẞ",
                0xe3: "à",
                0xe4: "á",
                0xe5: "â",
                0xe6: "ä",
                0xe7: "ç",
                0xe8: "è",
                0xe9: "é",
                0xea: "ê",
                0xeb: "ë",
                0xec: "ì",
                0xed: "í",
                0xee: "î",
                0xef: "ï",
                0xf0: "ñ",
                0xf1: "ò",
                0xf2: "ó",
                0xf3: "ô",
                0xf4: "ö",
                0xf5: "ù",
                0xf6: "ú",
                0xf7: "û",
                0xf8: "ü",
                0xf9: "°",
                0xFA: "{---}",
                0xfb: "》",
                0xfc: "《"}
decode_table = decode_table | \
               {i: "{" + f"0x{i:02X}" + "}" for i in range(0xFF) if i not in decode_table.keys()}
encode_table = {v: k for k, v in decode_table.items()} | \
               {"{" + f"0x{i:02X}" + "}": i for i in range(0xFF) if i not in decode_table.keys()} | \
               {"{" + f"{i:#02x}" + "}": i for i in range(0xFF) if i not in decode_table.keys()} | \
               {"{" + f"{i:#02X}" + "}": i for i in range(0xFF) if i not in decode_table.keys()} | \
               {"{" + f"0X{i:02x}" + "}": i for i in range(0xFF) if i not in decode_table.keys()}
decode_table_jp = {0x01: " ",
                   0x21: "0",
                   0x22: "1",
                   0x23: "2",
                   0x24: "3",
                   0x25: "4",
                   0x26: "5",
                   0x27: "6",
                   0x28: "7",
                   0x29: "8",
                   0x2a: "9",
                   0x2b: "+",
                   0x2c: "-",
                   0x2e: "A",
                   0x2f: "B",
                   0x30: "C",
                   0x31: "D",
                   0x32: "E",
                   0x33: "F",
                   0x34: "G",
                   0x35: "H",
                   0x36: "I",
                   0x37: "J",
                   0x38: "K",
                   0x39: "L",
                   0x3a: "M",
                   0x3b: "N",
                   0x3c: "O",
                   0x3d: "P",
                   0x3e: "Q",
                   0x3f: "R",
                   0x40: "S",
                   0x41: "T",
                   0x42: "U",
                   0x43: "V",
                   0x44: "W",
                   0x45: "X",
                   0x46: "Y",
                   0x47: "Z",
                   0x48: "!",
                   0x49: "?",
                   0x4a: "%",
                   0x4b: "/",
                   0x4f: ".",
                   0x50: ",",
                   0x51: ".",
                   0x52: ":",
                   0x53: "…",
                   0x55: "ー",
                   0x56: "~",
                   0x71: "X",
                   0x90: "あ",
                   0x91: "い",
                   0x92: "う",
                   0x93: "え",
                   0x94: "お",
                   0x95: "か",
                   0x96: "き",
                   0x97: "く",
                   0x98: "け",
                   0x99: "こ",
                   0x9a: "さ",
                   0x9b: "し",
                   0x9c: "す",
                   0x9d: "せ",
                   0x9e: "そ",
                   0x9f: "た",
                   0xa0: "ち",
                   0xa1: "つ",
                   0xa2: "て",
                   0xa3: "と",
                   0xa4: "な",
                   0xa5: "に",
                   0xa6: "ぬ",
                   0xa7: "ね",
                   0xa8: "の",
                   0xa9: "は",
                   0xaa: "ひ",
                   0xab: "ふ",
                   0xac: "へ",
                   0xad: "ほ",
                   0xae: "ま",
                   0xaf: "み",
                   0xb0: "む",
                   0xb1: "め",
                   0xb2: "も",
                   0xb3: "や",
                   0xb4: "ゆ",
                   0xb5: "よ",
                   0xb6: "ら",
                   0xb7: "り",
                   0xb8: "る",
                   0xb9: "れ",
                   0xba: "ろ",
                   0xbb: "わ",
                   0xbc: "を",
                   0xbd: "ん",
                   0xbe: "が",
                   0xbf: "ぎ",
                   0xc0: "ぐ",
                   0xc1: "げ",
                   0xc2: "ご",
                   0xc3: "ざ",
                   0xc2: "ご",
                   0xc3: "ざ",
                   0xc4: "じ",
                   0xc5: "ず",
                   0xc6: "ぜ",
                   0xc7: "ぞ",
                   0xc8: "だ",
                   0xc9: "ぢ",
                   0xca: "づ",
                   0xcb: "で",
                   0xcc: "ど",
                   0xcd: "ば",
                   0xce: "び",
                   0xcf: "ぶ",
                   0xd0: "べ",
                   0xd1: "ぼ",
                   0xd2: "ぱ",
                   0xd3: "ぴ",
                   0xd4: "ぷ",
                   0xd5: "ぺ",
                   0xd6: "ぽ",
                   0xd7: "ぁ",
                   0xd8: "ぃ",
                   0xd9: "ぅ",
                   0xda: "ぇ",
                   0xdb: "ぉ",
                   0xdc: "ゃ",
                   0xdd: "ゅ",
                   0xde: "ょ",
                   0xdf: "っ",
                   0xe0: "ア",
                   0xe1: "イ",
                   0xe2: "ウ",
                   0xe3: "エ",
                   0xe4: "オ",
                   0xe5: "カ",
                   0xe6: "キ",
                   0xe7: "ク",
                   0xe8: "ケ",
                   0xe9: "コ",
                   0xea: "サ",
                   0xeb: "シ",
                   0xec: "ス",
                   0xed: "セ",
                   0xee: "ソ",
                   0xef: "タ",
                   0xf0: "チ",
                   0xf1: "ツ",
                   0xf2: "テ",
                   0xf3: "ト",
                   0xf4: "ナ",
                   0xf5: "ニ",
                   0xf6: "ヌ",
                   0xf7: "ネ",
                   0xf8: "ノ",
                   0xf9: "ハ",
                   0xfa: "ヒ",
                   0xfb: "フ",
                   0xfc: "ヘ",
                   0xfd: "ホ",
                   0xfe: "マ",
                   0xff: "ミ",
                   #0x1819: "ム",
                   0x1900: "ム",
                   0x1901: "メ",
                   0x1902: "モ",
                   0x1903: "ヤ",
                   0x1904: "ユ",
                   0x1905: "ヨ",
                   0x1906: "ラ",
                   0x1907: "リ",
                   0x1908: "ル",
                   0x1909: "レ",
                   0x190a: "ロ",
                   0x190b: "ワ",
                   0x190c: "ヲ",
                   0x190d: "ン",
                   0x190e: "ガ",
                   0x190f: "ギ",
                   0x1910: "グ",
                   0x1911: "ゲ",
                   0x1912: "ゴ",
                   0x1913: "ザ",
                   0x1914: "ジ",
                   0x1915: "ズ",
                   0x1916: "ゼ",
                   0x1917: "ゾ",
                   0x1918: "ダ",
                   0x1919: "ヂ",
                   0x191a: "ヅ",
                   0x191b: "デ",
                   0x191c: "ド",
                   0x191d: "バ",
                   0x191e: "ビ",
                   0x191f: "ブ",
                   0x1920: "ベ",
                   0x1921: "ボ",
                   0x1922: "ヴ",
                   0x1923: "パ",
                   0x1924: "ピ",
                   0x1925: "プ",
                   0x1926: "ペ",
                   0x1927: "ポ",
                   0x1928: "ァ",
                   0x1929: "ィ",
                   0x192a: "ゥ",
                   0x192b: "ェ",
                   0x192c: "ォ",
                   0x192d: "ャ",
                   0x192e: "ュ",
                   0x192f: "ョ",
                   0x1930: "ッ"}
encode_table_jp = {v: k for k, v in decode_table_jp.items() if k != 0x00}

# Step 2: encode/decode functions
def kh1us_encode(input_str):
    isseq = False
    seq = []
    i = 0
    out_bytes = bytearray()
    for ch in input_str:
        if ch == "{" and "}" in input_str[i:]:
            isseq = True
        if isseq and ch == "}":
            ch = "".join(seq) + ch
            isseq = False
        if isseq:
            seq.append(ch)
        elif len(seq) > 0:
            seq = []
        if not isseq:
            n = encode_table.get(ch, 0x01)
            out_bytes += bytearray(n.to_bytes((n.bit_length() + 7) // 8, "big"))
        i += 1
    out_bytes.append(0x00)
    return (bytes(out_bytes), len(input_str))

def kh1us_decode(input_bytes):
    isseq = False
    iscolor = False
    s = 0
    seq = []
    out_chars = []
    for b in input_bytes:
        if b == 0x00 and not isseq:
            break
        if b == 0x09:
            isseq = True
        if b == 0x08:
            iscolor = True
            isseq = True
        if isseq:
            seq.append(b)
            s += 1
        if not iscolor and s == 2:
            b = int.from_bytes(seq)
            s = 0
            seq = []
            isseq = False
        if s == 5:
            b = int.from_bytes(seq)
            s = 0
            isseq = False
            iscolor = False
        if not isseq:
            if len(seq) > 0:
                for i in seq:
                    out_chars.append("{" + f"0x{i:02X}" + "}")
                seq = []
            else:
                out_chars.append(decode_table.get(b, " "))
    return (''.join(out_chars), len(input_bytes))

def kh1jp_encode(input_str):
    out_bytes = bytearray()
    for ch in input_str:
        if encode_table_jp.get(ch, 0x01) > 255:
            out_bytes += bytearray(encode_table_jp.get(ch, 0x01).to_bytes(2, "big"))
        else:
            out_bytes.append(encode_table_jp.get(ch, 0x01))
    out_bytes.append(0x00)
    return (bytes(out_bytes), len(input_str))

def kh1jp_decode(input_bytes):
    out_chars = []
    i = 0
    while i < len(input_bytes):
        b = input_bytes[i]
        if b == 0x00:
            break
        if b == 0x19 and i + 1 < len(input_bytes):
            b = int.from_bytes(input_bytes[i:i+2])
            i += 1
        out_chars.append(decode_table_jp.get(b, " "))
        i += 1
    return ("".join(out_chars), len(input_bytes))

# Step 3: search function
def kh1codec(name):
    if name == "kh1us":
        return codecs.CodecInfo(
            name="kh1us",
            encode=kh1us_encode,
            decode=kh1us_decode
        )
    if name == "kh1jp":
        return codecs.CodecInfo(
            name="kh1jp",
            encode=kh1jp_encode,
            decode=kh1jp_decode
        )
    return None

# Step 4: register it
codecs.register(kh1codec)
